//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.PR.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeEarningsDeductionResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeEarningsDeductionResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.PR.Resources.Forms.EmployeeEarningsDeductionResx", typeof(EmployeeEarningsDeductionResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accrual.
        /// </summary>
        public static string Accrual {
            get {
                return ResourceManager.GetString("Accrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accrued.
        /// </summary>
        public static string Accrued {
            get {
                return ResourceManager.GetString("Accrued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance To Be Repaid.
        /// </summary>
        public static string AdvanceToBeRepaid {
            get {
                return ResourceManager.GetString("AdvanceToBeRepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available in Employee Timecards.
        /// </summary>
        public static string AvailableInEmployeeTimecards {
            get {
                return ResourceManager.GetString("AvailableInEmployeeTimecards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banked Time.
        /// </summary>
        public static string BankedTime {
            get {
                return ResourceManager.GetString("BankedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Percentage 1.
        /// </summary>
        public static string BillingPercentage1 {
            get {
                return ResourceManager.GetString("BillingPercentage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Percentage 2.
        /// </summary>
        public static string BillingPercentage2 {
            get {
                return ResourceManager.GetString("BillingPercentage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Percentage 3.
        /// </summary>
        public static string BillingPercentage3 {
            get {
                return ResourceManager.GetString("BillingPercentage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Percentage 4.
        /// </summary>
        public static string BillingPercentage4 {
            get {
                return ResourceManager.GetString("BillingPercentage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Percentage 5.
        /// </summary>
        public static string BillingPercentage5 {
            get {
                return ResourceManager.GetString("BillingPercentage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Percentage 6.
        /// </summary>
        public static string BillingPercentage6 {
            get {
                return ResourceManager.GetString("BillingPercentage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rates.
        /// </summary>
        public static string BillingRates {
            get {
                return ResourceManager.GetString("BillingRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carry-over.
        /// </summary>
        public static string Carryover {
            get {
                return ResourceManager.GetString("Carryover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Employee Template.
        /// </summary>
        public static string CopyEmployeeTemplate {
            get {
                return ResourceManager.GetString("CopyEmployeeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        public static string Deduction {
            get {
                return ResourceManager.GetString("Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default hours.
        /// </summary>
        public static string DefaultHours {
            get {
                return ResourceManager.GetString("DefaultHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution code.
        /// </summary>
        public static string DistributionCode {
            get {
                return ResourceManager.GetString("DistributionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning.
        /// </summary>
        public static string Earning {
            get {
                return ResourceManager.GetString("Earning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning/Deduction Description.
        /// </summary>
        public static string EarningDeductionDescription {
            get {
                return ResourceManager.GetString("EarningDeductionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Annual Maximum.
        /// </summary>
        public static string EmployeeAnnualMaximum {
            get {
                return ResourceManager.GetString("EmployeeAnnualMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Base Limit.
        /// </summary>
        public static string EmployeeBaseLimit {
            get {
                return ResourceManager.GetString("EmployeeBaseLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Calc Method.
        /// </summary>
        public static string EmployeeCalcMethod {
            get {
                return ResourceManager.GetString("EmployeeCalcMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Earning/Deduction.
        /// </summary>
        public static string EmployeeEarningDeduction {
            get {
                return ResourceManager.GetString("EmployeeEarningDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Lifetime Accumulation.
        /// </summary>
        public static string EmployeeLifetimeAccumulation {
            get {
                return ResourceManager.GetString("EmployeeLifetimeAccumulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Lifetime Maximum.
        /// </summary>
        public static string EmployeeLifetimeMaximum {
            get {
                return ResourceManager.GetString("EmployeeLifetimeMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Period Maximum.
        /// </summary>
        public static string EmployeePeriodMaximum {
            get {
                return ResourceManager.GetString("EmployeePeriodMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Period Minimum.
        /// </summary>
        public static string EmployeePeriodMinimum {
            get {
                return ResourceManager.GetString("EmployeePeriodMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Rate/Amt/Pct..
        /// </summary>
        public static string EmployeeRateAmtPct {
            get {
                return ResourceManager.GetString("EmployeeRateAmtPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Secondary Rate/Amt/Pct..
        /// </summary>
        public static string EmployeeSecondaryRateAmtPct {
            get {
                return ResourceManager.GetString("EmployeeSecondaryRateAmtPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Secondary Rate Effectiv.
        /// </summary>
        public static string EmployeeSecondaryRateEffectiv {
            get {
                return ResourceManager.GetString("EmployeeSecondaryRateEffectiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Amt/Pct..
        /// </summary>
        public static string EmployerAmtPct {
            get {
                return ResourceManager.GetString("EmployerAmtPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Annual Maximum.
        /// </summary>
        public static string EmployerAnnualMaximum {
            get {
                return ResourceManager.GetString("EmployerAnnualMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Base Limit.
        /// </summary>
        public static string EmployerBaseLimit {
            get {
                return ResourceManager.GetString("EmployerBaseLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Calc Method.
        /// </summary>
        public static string EmployerCalcMethod {
            get {
                return ResourceManager.GetString("EmployerCalcMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Lifetime Accumulation.
        /// </summary>
        public static string EmployerLifetimeAccumulation {
            get {
                return ResourceManager.GetString("EmployerLifetimeAccumulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Lifetime Maximum.
        /// </summary>
        public static string EmployerLifetimeMaximum {
            get {
                return ResourceManager.GetString("EmployerLifetimeMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Period Maximum.
        /// </summary>
        public static string EmployerPeriodMaximum {
            get {
                return ResourceManager.GetString("EmployerPeriodMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Period Minimum.
        /// </summary>
        public static string EmployerPeriodMinimum {
            get {
                return ResourceManager.GetString("EmployerPeriodMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Secondary Amt/Pct..
        /// </summary>
        public static string EmployerSecondaryAmtPct {
            get {
                return ResourceManager.GetString("EmployerSecondaryAmtPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Secondary Rate Effectiv.
        /// </summary>
        public static string EmployerSecondaryRateEffectiv {
            get {
                return ResourceManager.GetString("EmployerSecondaryRateEffectiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR EmployeeEarningsDeduction.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Reimbursement.
        /// </summary>
        public static string ExpenseReimbursement {
            get {
                return ResourceManager.GetString("ExpenseReimbursement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in Regular Rate OT Calc.
        /// </summary>
        public static string IncludeInRegularRateOTCalc {
            get {
                return ResourceManager.GetString("IncludeInRegularRateOTCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Optional Fields.
        /// </summary>
        public static string InsertOptionalFields {
            get {
                return ResourceManager.GetString("InsertOptionalFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs Alloc Based on Calc Base.
        /// </summary>
        public static string JobsAllocBasedOnCalcBase {
            get {
                return ResourceManager.GetString("JobsAllocBasedOnCalcBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Optional Fields.
        /// </summary>
        public static string NumberOfOptionalFields {
            get {
                return ResourceManager.GetString("NumberOfOptionalFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Command Code.
        /// </summary>
        public static string ProcessCommandCode {
            get {
                return ResourceManager.GetString("ProcessCommandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVED - Segment Name 4.
        /// </summary>
        public static string RESERVEDSegmentName4 {
            get {
                return ResourceManager.GetString("RESERVEDSegmentName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVED - Segment Name 5.
        /// </summary>
        public static string RESERVEDSegmentName5 {
            get {
                return ResourceManager.GetString("RESERVEDSegmentName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVED - Segment Name 6.
        /// </summary>
        public static string RESERVEDSegmentName6 {
            get {
                return ResourceManager.GetString("RESERVEDSegmentName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Name 1.
        /// </summary>
        public static string SegmentName1 {
            get {
                return ResourceManager.GetString("SegmentName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Name 2.
        /// </summary>
        public static string SegmentName2 {
            get {
                return ResourceManager.GetString("SegmentName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Name 3.
        /// </summary>
        public static string SegmentName3 {
            get {
                return ResourceManager.GetString("SegmentName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick.
        /// </summary>
        public static string Sick {
            get {
                return ResourceManager.GetString("Sick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Employee.
        /// </summary>
        public static string TemplateEmployee {
            get {
                return ResourceManager.GetString("TemplateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        public static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers&apos; Compensation Code.
        /// </summary>
        public static string WorkersCompensationCode {
            get {
                return ResourceManager.GetString("WorkersCompensationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers Comp. Group.
        /// </summary>
        public static string WorkersCompGroup {
            get {
                return ResourceManager.GetString("WorkersCompGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
