//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.GL.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountPermissionsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountPermissionsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.GL.Resources.Forms.AccountPermissionsResx", typeof(AccountPermissionsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Permission.
        /// </summary>
        public static string AccountPermission {
            get {
                return ResourceManager.GetString("AccountPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/L Account Permissions.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted From Account.
        /// </summary>
        public static string FormattedFromAccount {
            get {
                return ResourceManager.GetString("FormattedFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted To Account.
        /// </summary>
        public static string FormattedToAccount {
            get {
                return ResourceManager.GetString("FormattedToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        public static string FromAccount {
            get {
                return ResourceManager.GetString("FromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Segment.
        /// </summary>
        public static string FromSegment {
            get {
                return ResourceManager.GetString("FromSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From User ID.
        /// </summary>
        public static string FromUserID {
            get {
                return ResourceManager.GetString("FromUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment_Permissions.
        /// </summary>
        public static string GL0052 {
            get {
                return ResourceManager.GetString("GL0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_Permissions.
        /// </summary>
        public static string GL0053 {
            get {
                return ResourceManager.GetString("GL0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string GL0054 {
            get {
                return ResourceManager.GetString("GL0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Restriction Records Switch.
        /// </summary>
        public static string HasRestrictionRecordsSwitch {
            get {
                return ResourceManager.GetString("HasRestrictionRecordsSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID {0} does not exist or cannot be used for account permissions..
        /// </summary>
        public static string IDNotExist {
            get {
                return ResourceManager.GetString("IDNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line No..
        /// </summary>
        public static string LineNo {
            get {
                return ResourceManager.GetString("LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Account Permissions Information.
        /// </summary>
        public static string PrintPopUpTitle {
            get {
                return ResourceManager.GetString("PrintPopUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        public static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        public static string ToAccount {
            get {
                return ResourceManager.GetString("ToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Segment.
        /// </summary>
        public static string ToSegment {
            get {
                return ResourceManager.GetString("ToSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To User ID.
        /// </summary>
        public static string ToUserID {
            get {
                return ResourceManager.GetString("ToUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find User.
        /// </summary>
        public static string UserHambergerMenuItemText {
            get {
                return ResourceManager.GetString("UserHambergerMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
