//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.AP.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _1099CPRSCodesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _1099CPRSCodesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.AP.Resources.Forms.1099CPRSCodesResx", typeof(_1099CPRSCodesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1099.
        /// </summary>
        public static string _1099 {
            get {
                return ResourceManager.GetString("_1099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Type.
        /// </summary>
        public static string AmountType {
            get {
                return ResourceManager.GetString("AmountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1099_CPRS Codes.
        /// </summary>
        public static string AP0007 {
            get {
                return ResourceManager.GetString("AP0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPRS.
        /// </summary>
        public static string CPRS {
            get {
                return ResourceManager.GetString("CPRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1099/CPRS Code Description.
        /// </summary>
        public static string CPRSCodeDesc {
            get {
                return ResourceManager.GetString("CPRSCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/P 1099/CPRS Codes.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Amount to Report.
        /// </summary>
        public static string MinAmtToRpt {
            get {
                return ResourceManager.GetString("MinAmtToRpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1099-Misc.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1099-Nec.
        /// </summary>
        public static string Nec {
            get {
                return ResourceManager.GetString("Nec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T5018.
        /// </summary>
        public static string T5018 {
            get {
                return ResourceManager.GetString("T5018", resourceCulture);
            }
        }
    }
}
