//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.CS.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchedulesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchedulesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.CS.Resources.Forms.SchedulesResx", typeof(SchedulesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string CS0030 {
            get {
                return ResourceManager.GetString("CS0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Run.
        /// </summary>
        public static string CurrentRun {
            get {
                return ResourceManager.GetString("CurrentRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DAILY {
            get {
                return ResourceManager.GetString("DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string DAYS {
            get {
                return ResourceManager.GetString("DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Month.
        /// </summary>
        public static string DOM {
            get {
                return ResourceManager.GetString("DOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Week.
        /// </summary>
        public static string DOW {
            get {
                return ResourceManager.GetString("DOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string EVERY {
            get {
                return ResourceManager.GetString("EVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Date.
        /// </summary>
        public static string FilterDate {
            get {
                return ResourceManager.GetString("FilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtration.
        /// </summary>
        public static string Filtration {
            get {
                return ResourceManager.GetString("Filtration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and.
        /// </summary>
        public static string FIRSTAND {
            get {
                return ResourceManager.GetString("FIRSTAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday Call.
        /// </summary>
        public static string FridayCall {
            get {
                return ResourceManager.GetString("FridayCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Due?.
        /// </summary>
        public static string IsDue {
            get {
                return ResourceManager.GetString("IsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Types.
        /// </summary>
        public static string JobTypes {
            get {
                return ResourceManager.GetString("JobTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Run Date.
        /// </summary>
        public static string LastRunDate {
            get {
                return ResourceManager.GetString("LastRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to and last day of the month.
        /// </summary>
        public static string LDOM {
            get {
                return ResourceManager.GetString("LDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday Call.
        /// </summary>
        public static string MondayCall {
            get {
                return ResourceManager.GetString("MondayCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MONTHLY {
            get {
                return ResourceManager.GetString("MONTHLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month(s).
        /// </summary>
        public static string MONTHS {
            get {
                return ResourceManager.GetString("MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Possible Run Date.
        /// </summary>
        public static string NextPossibleRunDate {
            get {
                return ResourceManager.GetString("NextPossibleRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Run.
        /// </summary>
        public static string NextRun {
            get {
                return ResourceManager.GetString("NextRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Run Date.
        /// </summary>
        public static string NextRunDate {
            get {
                return ResourceManager.GetString("NextRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the.
        /// </summary>
        public static string ONTHE {
            get {
                return ResourceManager.GetString("ONTHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Details.
        /// </summary>
        public static string PFSDFrmCap {
            get {
                return ResourceManager.GetString("PFSDFrmCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred and Schedule Details could not be created. Please try again..
        /// </summary>
        public static string PFSDFrmSetupFailTxt {
            get {
                return ResourceManager.GetString("PFSDFrmSetupFailTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Periods.
        /// </summary>
        public static string RECPER {
            get {
                return ResourceManager.GetString("RECPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind in Advance.
        /// </summary>
        public static string RemindAdvance {
            get {
                return ResourceManager.GetString("RemindAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string REMINDERS {
            get {
                return ResourceManager.GetString("REMINDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder List.
        /// </summary>
        public static string ReminderList {
            get {
                return ResourceManager.GetString("ReminderList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reminders To.
        /// </summary>
        public static string RemindersTo {
            get {
                return ResourceManager.GetString("RemindersTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders To.
        /// </summary>
        public static string ReminderTo {
            get {
                return ResourceManager.GetString("ReminderTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Date.
        /// </summary>
        public static string RunDate {
            get {
                return ResourceManager.GetString("RunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday Call.
        /// </summary>
        public static string SaturdayCall {
            get {
                return ResourceManager.GetString("SaturdayCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the specified schedule..
        /// </summary>
        public static string SchedNotEXIST {
            get {
                return ResourceManager.GetString("SchedNotEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string SchedRecType {
            get {
                return ResourceManager.GetString("SchedRecType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Button.
        /// </summary>
        public static string ScheduleButton {
            get {
                return ResourceManager.GetString("ScheduleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Code.
        /// </summary>
        public static string ScheduleCode {
            get {
                return ResourceManager.GetString("ScheduleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Description.
        /// </summary>
        public static string ScheduleCodeDesc {
            get {
                return ResourceManager.GetString("ScheduleCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ScheduleDetailDesc {
            get {
                return ResourceManager.GetString("ScheduleDetailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Start Date.
        /// </summary>
        public static string ScheduleStartDate {
            get {
                return ResourceManager.GetString("ScheduleStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-monthly.
        /// </summary>
        public static string SEMIMON {
            get {
                return ResourceManager.GetString("SEMIMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Run Date.
        /// </summary>
        public static string SuggestedRunDate {
            get {
                return ResourceManager.GetString("SuggestedRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday Call.
        /// </summary>
        public static string SundayCall {
            get {
                return ResourceManager.GetString("SundayCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string THE {
            get {
                return ResourceManager.GetString("THE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These Work Days.
        /// </summary>
        public static string THESEWORK {
            get {
                return ResourceManager.GetString("THESEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday Call.
        /// </summary>
        public static string ThursdayCall {
            get {
                return ResourceManager.GetString("ThursdayCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday Call.
        /// </summary>
        public static string TuesdayCall {
            get {
                return ResourceManager.GetString("TuesdayCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the specified User ID..
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mode.
        /// </summary>
        public static string UserMode {
            get {
                return ResourceManager.GetString("UserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday Call.
        /// </summary>
        public static string WednesdayCall {
            get {
                return ResourceManager.GetString("WednesdayCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week in Month.
        /// </summary>
        public static string WeekinMonth {
            get {
                return ResourceManager.GetString("WeekinMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string WEEKLY {
            get {
                return ResourceManager.GetString("WEEKLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week(s).
        /// </summary>
        public static string WEEKS {
            get {
                return ResourceManager.GetString("WEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string YEARLY {
            get {
                return ResourceManager.GetString("YEARLY", resourceCulture);
            }
        }
    }
}
