//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationDetailsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationDetailsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms.LocationDetailsResx", typeof(LocationDetailsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string Allowed {
            get {
                return ResourceManager.GetString("Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Not in Cost File.
        /// </summary>
        public static string CostNotinCostFile {
            get {
                return ResourceManager.GetString("CostNotinCostFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last Used.
        /// </summary>
        public static string DateLastUsed {
            get {
                return ResourceManager.GetString("DateLastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Location Activated.
        /// </summary>
        public static string DateLocationActivated {
            get {
                return ResourceManager.GetString("DateLocationActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this location detail record?.
        /// </summary>
        public static string DeleteICILOC {
            get {
                return ResourceManager.GetString("DeleteICILOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/C Location Details.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Details.
        /// </summary>
        public static string IC0290 {
            get {
                return ResourceManager.GetString("IC0290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Use.
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number.
        /// </summary>
        public static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time (SIA) cannot exceed 32,767..
        /// </summary>
        public static string LeadTimeErrorMessage {
            get {
                return ResourceManager.GetString("LeadTimeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Cost.
        /// </summary>
        public static string LOTCOST {
            get {
                return ResourceManager.GetString("LOTCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Cost....
        /// </summary>
        public static string LOTCOST1 {
            get {
                return ResourceManager.GetString("LOTCOST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have an inventory of non-stock items..
        /// </summary>
        public static string NonStockItemError {
            get {
                return ResourceManager.GetString("NonStockItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Uncosted Transactions.
        /// </summary>
        public static string NumberofUncontestedTransactions {
            get {
                return ResourceManager.GetString("NumberofUncontestedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing Unit.
        /// </summary>
        public static string PERCOSTINGUNIT {
            get {
                return ResourceManager.GetString("PERCOSTINGUNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking Sequence.
        /// </summary>
        public static string PickingSequence {
            get {
                return ResourceManager.GetString("PickingSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity on Hand (Last Day End).
        /// </summary>
        public static string QuantityonHandLastDayEnd {
            get {
                return ResourceManager.GetString("QuantityonHandLastDayEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Cost.
        /// </summary>
        public static string SERIALCOST {
            get {
                return ResourceManager.GetString("SERIALCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Cost....
        /// </summary>
        public static string SERIALCOST1 {
            get {
                return ResourceManager.GetString("SERIALCOST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Costs.
        /// </summary>
        public static string TitleLOTCOST {
            get {
                return ResourceManager.GetString("TitleLOTCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Costs.
        /// </summary>
        public static string TitleSERIALCOST {
            get {
                return ResourceManager.GetString("TitleSERIALCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string VENDOR {
            get {
                return ResourceManager.GetString("VENDOR", resourceCulture);
            }
        }
    }
}
