//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms.OptionsResx", typeof(OptionsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate By.
        /// </summary>
        public static string AccumulateStatBy {
            get {
                return ResourceManager.GetString("AccumulateStatBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Cost for Items on Receipt Returns.
        /// </summary>
        public static string AddCostOnRecptRtn {
            get {
                return ResourceManager.GetString("AddCostOnRecptRtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must add an item number segment to the end of the list. Scroll to the end of the list before adding an item number segment..
        /// </summary>
        public static string AddNotInsert {
            get {
                return ResourceManager.GetString("AddNotInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aging Periods (Days).
        /// </summary>
        public static string AgingPeriods {
            get {
                return ResourceManager.GetString("AgingPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Edit of Statistics.
        /// </summary>
        public static string AllowEditStats {
            get {
                return ResourceManager.GetString("AllowEditStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Fractional Quantities.
        /// </summary>
        public static string AllowFractQty {
            get {
                return ResourceManager.GetString("AllowFractQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Items at All Locations.
        /// </summary>
        public static string AllowItemAtAllLocation {
            get {
                return ResourceManager.GetString("AllowItemAtAllLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Negative Inventory Levels.
        /// </summary>
        public static string AllowNegativeQty {
            get {
                return ResourceManager.GetString("AllowNegativeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Receipt of Non-Stock Items.
        /// </summary>
        public static string AllowRecptNonStkItem {
            get {
                return ResourceManager.GetString("AllowRecptNonStkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Amount 1 Name.
        /// </summary>
        public static string AlternateAmtName1 {
            get {
                return ResourceManager.GetString("AlternateAmtName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Amount 2 Name.
        /// </summary>
        public static string AlternateAmtName2 {
            get {
                return ResourceManager.GetString("AlternateAmtName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annually.
        /// </summary>
        public static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Number must be between 1 and 22 characters in length..
        /// </summary>
        public static string AssemNoLengthMessage {
            get {
                return ResourceManager.GetString("AssemNoLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly number prefix appended to next assembly number exceeds specified length of {0} characters..
        /// </summary>
        public static string AssemPrefixLengthMessage {
            get {
                return ResourceManager.GetString("AssemPrefixLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-monthly.
        /// </summary>
        public static string Bimonthly {
            get {
                return ResourceManager.GetString("Bimonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-weekly.
        /// </summary>
        public static string Biweekly {
            get {
                return ResourceManager.GetString("Biweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Year.
        /// </summary>
        public static string CalendarYear {
            get {
                return ResourceManager.GetString("CalendarYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aging periods must be in ascending order..
        /// </summary>
        public static string ChangeInAgingPeriod {
            get {
                return ResourceManager.GetString("ChangeInAgingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should change this option only at year end. If you change it partway through a year, edit the statistics to correct the totals for each period..
        /// </summary>
        public static string ChangeInStatistics {
            get {
                return ResourceManager.GetString("ChangeInStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ColumnttlValidate {
            get {
                return ResourceManager.GetString("ColumnttlValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Items During.
        /// </summary>
        public static string Costduring {
            get {
                return ResourceManager.GetString("Costduring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Goods in Transit Location.
        /// </summary>
        public static string DefaultGoodsInTransitLocation {
            get {
                return ResourceManager.GetString("DefaultGoodsInTransitLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Item Structure.
        /// </summary>
        public static string DefaultItemStruct {
            get {
                return ResourceManager.GetString("DefaultItemStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Rate Type.
        /// </summary>
        public static string DefaultRateType {
            get {
                return ResourceManager.GetString("DefaultRateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Weight UOM.
        /// </summary>
        public static string DefaultWeightUOM {
            get {
                return ResourceManager.GetString("DefaultWeightUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassembly Number.
        /// </summary>
        public static string DocnumberDisassembly {
            get {
                return ResourceManager.GetString("DocnumberDisassembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Return Number.
        /// </summary>
        public static string DocnumberShipmentReturn {
            get {
                return ResourceManager.GetString("DocnumberShipmentReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Receipt Number.
        /// </summary>
        public static string DocnumberTransitReceipt {
            get {
                return ResourceManager.GetString("DocnumberTransitReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Number.
        /// </summary>
        public static string DocumentAdjustmentNumber {
            get {
                return ResourceManager.GetString("DocumentAdjustmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Number.
        /// </summary>
        public static string DocumentAssemblyNumber {
            get {
                return ResourceManager.GetString("DocumentAssemblyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine Number.
        /// </summary>
        public static string DocumentCombineNumber {
            get {
                return ResourceManager.GetString("DocumentCombineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Usage Number.
        /// </summary>
        public static string DocumentInternalUsageNumber {
            get {
                return ResourceManager.GetString("DocumentInternalUsageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Numbers.
        /// </summary>
        public static string DocumentNumbers {
            get {
                return ResourceManager.GetString("DocumentNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Number.
        /// </summary>
        public static string DocumentRecallNumber {
            get {
                return ResourceManager.GetString("DocumentRecallNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Number.
        /// </summary>
        public static string DocumentReceiptNumber {
            get {
                return ResourceManager.GetString("DocumentReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Number.
        /// </summary>
        public static string DocumentReconciliationNumber {
            get {
                return ResourceManager.GetString("DocumentReconciliationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Number.
        /// </summary>
        public static string DocumentReleaseNumber {
            get {
                return ResourceManager.GetString("DocumentReleaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Number.
        /// </summary>
        public static string DocumentShipmentNumber {
            get {
                return ResourceManager.GetString("DocumentShipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Number.
        /// </summary>
        public static string DocumentSplitNumber {
            get {
                return ResourceManager.GetString("DocumentSplitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Number.
        /// </summary>
        public static string DocumentTransferNumber {
            get {
                return ResourceManager.GetString("DocumentTransferNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/C Options.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Weeks.
        /// </summary>
        public static string FourWeeks {
            get {
                return ResourceManager.GetString("FourWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Defaults.
        /// </summary>
        public static string FramecaptionItemDefaults {
            get {
                return ResourceManager.GetString("FramecaptionItemDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Statistics.
        /// </summary>
        public static string FramecaptionItemStatistics {
            get {
                return ResourceManager.GetString("FramecaptionItemStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Options.
        /// </summary>
        public static string FramecaptionProcessingOption {
            get {
                return ResourceManager.GetString("FramecaptionProcessingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Number.
        /// </summary>
        public static string GrdcaptionNextNumber {
            get {
                return ResourceManager.GetString("GrdcaptionNextNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string GrdcolumnttlSeparator {
            get {
                return ResourceManager.GetString("GrdcolumnttlSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Structures.
        /// </summary>
        public static string ItemStructureFinderTitle {
            get {
                return ResourceManager.GetString("ItemStructureFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Item Statistics.
        /// </summary>
        public static string KeepItemStats {
            get {
                return ResourceManager.GetString("KeepItemStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Transaction History.
        /// </summary>
        public static string KeepTransHist {
            get {
                return ResourceManager.GetString("KeepTransHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of segments is 10..
        /// </summary>
        public static string MaxSegments {
            get {
                return ResourceManager.GetString("MaxSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicurrency.
        /// </summary>
        public static string MultiCurrency {
            get {
                return ResourceManager.GetString("MultiCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Day End Number.
        /// </summary>
        public static string NextDayEndNum {
            get {
                return ResourceManager.GetString("NextDayEndNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Only Defined UOM.
        /// </summary>
        public static string OnlyUseDefinedUOM {
            get {
                return ResourceManager.GetString("OnlyUseDefinedUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Posting Date.
        /// </summary>
        public static string PostingDateDefault {
            get {
                return ResourceManager.GetString("PostingDateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt to Delete During Posting.
        /// </summary>
        public static string PrompttoDelete {
            get {
                return ResourceManager.GetString("PrompttoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prorate.
        /// </summary>
        public static string Prorate {
            get {
                return ResourceManager.GetString("Prorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type.
        /// </summary>
        public static string RateTypeFinderTitle {
            get {
                return ResourceManager.GetString("RateTypeFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Segment Length..
        /// </summary>
        public static string SegmentLength {
            get {
                return ResourceManager.GetString("SegmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Name.
        /// </summary>
        public static string SegmentName {
            get {
                return ResourceManager.GetString("SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment Number.
        /// </summary>
        public static string SegmentNumber {
            get {
                return ResourceManager.GetString("SegmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-annually.
        /// </summary>
        public static string Semiannually {
            get {
                return ResourceManager.GetString("Semiannually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separators Used in Item Structures.
        /// </summary>
        public static string SepUsedInItemStruct {
            get {
                return ResourceManager.GetString("SepUsedInItemStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Date.
        /// </summary>
        public static string SessionDate {
            get {
                return ResourceManager.GetString("SessionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Days.
        /// </summary>
        public static string SevenDays {
            get {
                return ResourceManager.GetString("SevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Subledger Transactions and Audit Information During.
        /// </summary>
        public static string SLAUduring {
            get {
                return ResourceManager.GetString("SLAUduring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type.
        /// </summary>
        public static string StatPeriodType {
            get {
                return ResourceManager.GetString("StatPeriodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Code Description.
        /// </summary>
        public static string StructureCodeDescription {
            get {
                return ResourceManager.GetString("StructureCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string TabcaptionCompany {
            get {
                return ResourceManager.GetString("TabcaptionCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing.
        /// </summary>
        public static string TabcaptionCosting {
            get {
                return ResourceManager.GetString("TabcaptionCosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string TabcaptionDocuments {
            get {
                return ResourceManager.GetString("TabcaptionDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots.
        /// </summary>
        public static string TabcaptionLots {
            get {
                return ResourceManager.GetString("TabcaptionLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string TabcaptionProcessing {
            get {
                return ResourceManager.GetString("TabcaptionProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After setting a lot mask structure separator so it is not used, it cannot be reset to in use again. Do you want to proceed?.
        /// </summary>
        public static string WarningLotsepOnOff {
            get {
                return ResourceManager.GetString("WarningLotsepOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After setting an item separator so it is not used, it cannot be reset to in use again. Do you want to proceed?.
        /// </summary>
        public static string WarningSeparatorOnOff {
            get {
                return ResourceManager.GetString("WarningSeparatorOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After setting a serial mask structure separator so it is not used, it cannot be reset to in use again. Do you want to proceed?.
        /// </summary>
        public static string WarningSerialsepOnOff {
            get {
                return ResourceManager.GetString("WarningSerialsepOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Units of Measure.
        /// </summary>
        public static string WeightUnitOfMeasureFinderTitle {
            get {
                return ResourceManager.GetString("WeightUnitOfMeasureFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With.
        /// </summary>
        public static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
    }
}
