//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SerialLotReconciliationsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerialLotReconciliationsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms.SerialLotReconciliationsResx", typeof(SerialLotReconciliationsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to Document.
        /// </summary>
        public static string ApplyToDoc {
            get {
                return ResourceManager.GetString("ApplyToDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To Invoice Number.
        /// </summary>
        public static string ApplyToInvoiceNumber {
            get {
                return ResourceManager.GetString("ApplyToInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Allocate From.
        /// </summary>
        public static string AutoAllocateFrom {
            get {
                return ResourceManager.GetString("AutoAllocateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Generate.
        /// </summary>
        public static string AutoGen {
            get {
                return ResourceManager.GetString("AutoGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all the lot numbers from the list?.
        /// </summary>
        public static string ConfirmClearLots {
            get {
                return ResourceManager.GetString("ConfirmClearLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all the serial numbers from the list?.
        /// </summary>
        public static string ConfirmClearSerials {
            get {
                return ResourceManager.GetString("ConfirmClearSerials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the lot number?.
        /// </summary>
        public static string ConfirmDeleteLot {
            get {
                return ResourceManager.GetString("ConfirmDeleteLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the serial number?.
        /// </summary>
        public static string ConfirmDeleteSerial {
            get {
                return ResourceManager.GetString("ConfirmDeleteSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to post this {0}?.
        /// </summary>
        public static string ConfirmPost {
            get {
                return ResourceManager.GetString("ConfirmPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Usage Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting Date.
        /// </summary>
        public static string DateBus {
            get {
                return ResourceManager.GetString("DateBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Lot Has.
        /// </summary>
        public static string EachLotHas {
            get {
                return ResourceManager.GetString("EachLotHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/C Serial/Lot Reconciliations.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to display kit component items?.
        /// </summary>
        public static string KITITEMINVOICE {
            get {
                return ResourceManager.GetString("KITITEMINVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0} is not active..
        /// </summary>
        public static string LOCATIONINACTIVE {
            get {
                return ResourceManager.GetString("LOCATIONINACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial/Lot Item is not allowed at this location..
        /// </summary>
        public static string LOCATIONNOTALLOWED {
            get {
                return ResourceManager.GetString("LOCATIONNOTALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number {0} is not available..
        /// </summary>
        public static string LotNotAvailable {
            get {
                return ResourceManager.GetString("LotNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lot number is not valid for the current lot number mask..
        /// </summary>
        public static string LOTNUMWRONGFORMAT {
            get {
                return ResourceManager.GetString("LOTNUMWRONGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Quantity Required.
        /// </summary>
        public static string LotQtyRequired {
            get {
                return ResourceManager.GetString("LotQtyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an Invoice Number before specifying an Item Number..
        /// </summary>
        public static string NeedApplyToDoc {
            get {
                return ResourceManager.GetString("NeedApplyToDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Lot Number.
        /// </summary>
        public static string NextLotNumber {
            get {
                return ResourceManager.GetString("NextLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Serial Number.
        /// </summary>
        public static string NextSerialNumber {
            get {
                return ResourceManager.GetString("NextSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0} not found for Item {1}..
        /// </summary>
        public static string NOLOCATIONFORITEM {
            get {
                return ResourceManager.GetString("NOLOCATIONFORITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/E Invoice.
        /// </summary>
        public static string OEInvoice {
            get {
                return ResourceManager.GetString("OEInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P/O Invoice.
        /// </summary>
        public static string POInvoice {
            get {
                return ResourceManager.GetString("POInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity exceeds maximum allowable quantity..
        /// </summary>
        public static string QtyOverflow {
            get {
                return ResourceManager.GetString("QtyOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity cannot exceed the quantity available at the specified location..
        /// </summary>
        public static string QuantityExceedsLocation {
            get {
                return ResourceManager.GetString("QuantityExceedsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities cannot be less than zero..
        /// </summary>
        public static string QuantityNeg {
            get {
                return ResourceManager.GetString("QuantityNeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall.
        /// </summary>
        public static string Recall {
            get {
                return ResourceManager.GetString("Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation.
        /// </summary>
        public static string Reconciliation {
            get {
                return ResourceManager.GetString("Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Headers.
        /// </summary>
        public static string ReconciliationHeaders {
            get {
                return ResourceManager.GetString("ReconciliationHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Numbers Required.
        /// </summary>
        public static string SerialNumsRequired {
            get {
                return ResourceManager.GetString("SerialNumsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All transactions affecting inventory should be posted and Day End Processing run before using this transaction..
        /// </summary>
        public static string StartupWarning {
            get {
                return ResourceManager.GetString("StartupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Unit Of Measure.
        /// </summary>
        public static string StockUnitOfMeasure {
            get {
                return ResourceManager.GetString("StockUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used By.
        /// </summary>
        public static string UsedBy {
            get {
                return ResourceManager.GetString("UsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
