//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SerialLotGenerationResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerialLotGenerationResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms.SerialLotGenerationResx", typeof(SerialLotGenerationResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust All.
        /// </summary>
        public static string AdjustAll {
            get {
                return ResourceManager.GetString("AdjustAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Cost.
        /// </summary>
        public static string AdjustedCost {
            get {
                return ResourceManager.GetString("AdjustedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Cost.
        /// </summary>
        public static string AdjustmentCost {
            get {
                return ResourceManager.GetString("AdjustmentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated.
        /// </summary>
        public static string Allocated {
            get {
                return ResourceManager.GetString("Allocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation.
        /// </summary>
        public static string Allocation {
            get {
                return ResourceManager.GetString("Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lot numbers were allocated. There may not be any lots with enough quantity available to allocate. After running day end processing there may be lots with quantity available to allocate..
        /// </summary>
        public static string AllocLotNoneWarning {
            get {
                return ResourceManager.GetString("AllocLotNoneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all lot quantity required was allocated. There may not be more lots with enough quantity available to allocate. After running day end processing there may be more lots with quantity available to allocate..
        /// </summary>
        public static string AllocLotSomeWarning {
            get {
                return ResourceManager.GetString("AllocLotSomeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No serial numbers were allocated. There may not be any serials available to allocate. After running day end processing serials may be available to allocate..
        /// </summary>
        public static string AllocSerialNoneWarning {
            get {
                return ResourceManager.GetString("AllocSerialNoneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all the required serial numbers were allocated. There may not be more serials available to allocate. After running day end processing more serials may be available to allocate..
        /// </summary>
        public static string AllocSerialSomeWarning {
            get {
                return ResourceManager.GetString("AllocSerialSomeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign All.
        /// </summary>
        public static string AssignAll {
            get {
                return ResourceManager.GetString("AssignAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Alloc.
        /// </summary>
        public static string AutoAlloc {
            get {
                return ResourceManager.GetString("AutoAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Allocate From.
        /// </summary>
        public static string AutoAllocFrom {
            get {
                return ResourceManager.GetString("AutoAllocFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Gen.
        /// </summary>
        public static string AutoGen {
            get {
                return ResourceManager.GetString("AutoGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to auto-generate {0} numbers..
        /// </summary>
        public static string AutoGenFailedMessage {
            get {
                return ResourceManager.GetString("AutoGenFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Number cannot be blank..
        /// </summary>
        public static string CannotBeBlankErrorMessage {
            get {
                return ResourceManager.GetString("CannotBeBlankErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all the lot numbers from the list?.
        /// </summary>
        public static string ClearLotNumbersConfirmMessage {
            get {
                return ResourceManager.GetString("ClearLotNumbersConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all the serial numbers from the list?.
        /// </summary>
        public static string ClearSerialNumbersConfirmMessage {
            get {
                return ResourceManager.GetString("ClearSerialNumbersConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining lot adjustment costs are not zero..
        /// </summary>
        public static string CloseWithLotCostNoMatchMessage {
            get {
                return ResourceManager.GetString("CloseWithLotCostNoMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining lot quantity is not zero. You will not be able to save the record..
        /// </summary>
        public static string CloseWithLotRemainingMessage {
            get {
                return ResourceManager.GetString("CloseWithLotRemainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining serial and lot adjustment costs are not zero..
        /// </summary>
        public static string CloseWithSerialAndLotCostNoMatchMessage {
            get {
                return ResourceManager.GetString("CloseWithSerialAndLotCostNoMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the remaining serial and lot quantities are not zero. You will not be able to save the record..
        /// </summary>
        public static string CloseWithSerialAndLotRemainingMessage {
            get {
                return ResourceManager.GetString("CloseWithSerialAndLotRemainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining serial adjustment costs are not zero..
        /// </summary>
        public static string CloseWithSerialCostNoMatchMessage {
            get {
                return ResourceManager.GetString("CloseWithSerialCostNoMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remaining serial quantity is not zero. You will not be able to save the record..
        /// </summary>
        public static string CloseWithSerialRemainingMessage {
            get {
                return ResourceManager.GetString("CloseWithSerialRemainingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Adjust All.
        /// </summary>
        public static string CostAdjustAll {
            get {
                return ResourceManager.GetString("CostAdjustAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Adjusted.
        /// </summary>
        public static string CostAdjusted {
            get {
                return ResourceManager.GetString("CostAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row to delete..
        /// </summary>
        public static string DeletelineWarning {
            get {
                return ResourceManager.GetString("DeletelineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each Lot Has.
        /// </summary>
        public static string EachLotHas {
            get {
                return ResourceManager.GetString("EachLotHas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next lot number was blanked. The system cannot add/generate a lot number based on a blank next lot number..
        /// </summary>
        public static string EmptyNextLotNo {
            get {
                return ResourceManager.GetString("EmptyNextLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next serial number was blanked. The system cannot add/generate a serial number based on a blank next serial number..
        /// </summary>
        public static string EmptyNextSerialNumber {
            get {
                return ResourceManager.GetString("EmptyNextSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning. Expiry Date is earlier than Stock Date for lot {0}..
        /// </summary>
        public static string ExpiryDateBeforeStockDateWarning {
            get {
                return ResourceManager.GetString("ExpiryDateBeforeStockDateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fractional quantity cannot be used with a serialized item..
        /// </summary>
        public static string FractionalQty {
            get {
                return ResourceManager.GetString("FractionalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        public static string Generated {
            get {
                return ResourceManager.GetString("Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated/Allocated.
        /// </summary>
        public static string GeneratedAllocated {
            get {
                return ResourceManager.GetString("GeneratedAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        public static string Generation {
            get {
                return ResourceManager.GetString("Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation/Allocation.
        /// </summary>
        public static string GenerationAllocation {
            get {
                return ResourceManager.GetString("GenerationAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number.
        /// </summary>
        public static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots Assigned.
        /// </summary>
        public static string LAssigned {
            get {
                return ResourceManager.GetString("LAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Numbers Generation/Allocation.
        /// </summary>
        public static string LotEntity {
            get {
                return ResourceManager.GetString("LotEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Qty Required.
        /// </summary>
        public static string LotNoRequired {
            get {
                return ResourceManager.GetString("LotNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Numbers.
        /// </summary>
        public static string LotNumbers {
            get {
                return ResourceManager.GetString("LotNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next lot number is not valid for the current lot number mask..
        /// </summary>
        public static string LotNumberValidationMessage {
            get {
                return ResourceManager.GetString("LotNumberValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots.
        /// </summary>
        public static string Lots {
            get {
                return ResourceManager.GetString("Lots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots Adjusted.
        /// </summary>
        public static string LotsAdjusted {
            get {
                return ResourceManager.GetString("LotsAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots Received.
        /// </summary>
        public static string LotsReceived {
            get {
                return ResourceManager.GetString("LotsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocated.
        /// </summary>
        public static string LotsReturned {
            get {
                return ResourceManager.GetString("LotsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots Shipped.
        /// </summary>
        public static string LotsShipped {
            get {
                return ResourceManager.GetString("LotsShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Lot Number.
        /// </summary>
        public static string NextLotNo {
            get {
                return ResourceManager.GetString("NextLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Serial Number.
        /// </summary>
        public static string NextSerialNumber {
            get {
                return ResourceManager.GetString("NextSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next {0} number was blanked. The system cannot add/generate a {0} number based on a blank next {0} number..
        /// </summary>
        public static string NextSerialOrLotNumberBlankError {
            get {
                return ResourceManager.GetString("NextSerialOrLotNumberBlankError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} numbers were generated. Verify the item has a valid {0} number mask configured..
        /// </summary>
        public static string NoSerialOrLotNumberGeneratedWarning {
            get {
                return ResourceManager.GetString("NoSerialOrLotNumberGeneratedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not serialized or lotted: the serials/lot form will not be displayed..
        /// </summary>
        public static string NotSerializedLottedWarnMsg {
            get {
                return ResourceManager.GetString("NotSerializedLottedWarnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Adjusted.
        /// </summary>
        public static string QtyAdjusted {
            get {
                return ResourceManager.GetString("QtyAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Received.
        /// </summary>
        public static string QtyReceived {
            get {
                return ResourceManager.GetString("QtyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Returned.
        /// </summary>
        public static string QtyReturned {
            get {
                return ResourceManager.GetString("QtyReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Shipped.
        /// </summary>
        public static string QtyShipped {
            get {
                return ResourceManager.GetString("QtyShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Adjusted.
        /// </summary>
        public static string QuantityAdjusted {
            get {
                return ResourceManager.GetString("QuantityAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Received.
        /// </summary>
        public static string QuantityReceived {
            get {
                return ResourceManager.GetString("QuantityReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Returned.
        /// </summary>
        public static string QuantityReturned {
            get {
                return ResourceManager.GetString("QuantityReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Shipped.
        /// </summary>
        public static string QuantityShipped {
            get {
                return ResourceManager.GetString("QuantityShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive All.
        /// </summary>
        public static string ReceiveAll {
            get {
                return ResourceManager.GetString("ReceiveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} number {1} already exists..
        /// </summary>
        public static string RecordAlreadyExistError {
            get {
                return ResourceManager.GetString("RecordAlreadyExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the generated/allocated serials/lots will be cleaned up. Continue to proceed?.
        /// </summary>
        public static string RemoveSerialLotData {
            get {
                return ResourceManager.GetString("RemoveSerialLotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return All.
        /// </summary>
        public static string ReturnAll {
            get {
                return ResourceManager.GetString("ReturnAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials Assigned.
        /// </summary>
        public static string SAssgined {
            get {
                return ResourceManager.GetString("SAssgined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measure.
        /// </summary>
        public static string SAssignedUOM {
            get {
                return ResourceManager.GetString("SAssignedUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Numbers Generation/Allocation.
        /// </summary>
        public static string SerialEntity {
            get {
                return ResourceManager.GetString("SerialEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial/Lot Numbers Generation.
        /// </summary>
        public static string SerialLotEntity {
            get {
                return ResourceManager.GetString("SerialLotEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial/Lot Numbers.
        /// </summary>
        public static string SerialLotNumbers {
            get {
                return ResourceManager.GetString("SerialLotNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        public static string SerialNoGenerated {
            get {
                return ResourceManager.GetString("SerialNoGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string SerialNoRemaining {
            get {
                return ResourceManager.GetString("SerialNoRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Numbers Required.
        /// </summary>
        public static string SerialNoRequired {
            get {
                return ResourceManager.GetString("SerialNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Numbers.
        /// </summary>
        public static string SerialNumbers {
            get {
                return ResourceManager.GetString("SerialNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serial number is not valid for the current serial number mask..
        /// </summary>
        public static string SerialNumberValidationMessage {
            get {
                return ResourceManager.GetString("SerialNumberValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All required {0} numbers have been generated..
        /// </summary>
        public static string SerialOrLotNumberGeneratedWarning {
            get {
                return ResourceManager.GetString("SerialOrLotNumberGeneratedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials Adjusted.
        /// </summary>
        public static string SerialsAdjusted {
            get {
                return ResourceManager.GetString("SerialsAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials Received.
        /// </summary>
        public static string SerialsReceived {
            get {
                return ResourceManager.GetString("SerialsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials Returned.
        /// </summary>
        public static string SerialsReturned {
            get {
                return ResourceManager.GetString("SerialsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials Shipped.
        /// </summary>
        public static string SerialsShipped {
            get {
                return ResourceManager.GetString("SerialsShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship All.
        /// </summary>
        public static string ShipAll {
            get {
                return ResourceManager.GetString("ShipAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string Shipped {
            get {
                return ResourceManager.GetString("Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Assigned.
        /// </summary>
        public static string SQTYAssigned {
            get {
                return ResourceManager.GetString("SQTYAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Date.
        /// </summary>
        public static string StockDate {
            get {
                return ResourceManager.GetString("StockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure.
        /// </summary>
        public static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;Make Lots&apos; or &apos;Each Lot Has&apos; has to be zero but both cannot be zero.
        /// </summary>
        public static string ZeroWarning {
            get {
                return ResourceManager.GetString("ZeroWarning", resourceCulture);
            }
        }
    }
}
