//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContractCodesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractCodesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.IC.Resources.Forms.ContractCodesResx", typeof(ContractCodesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Code Description.
        /// </summary>
        public static string ContractCodeDescription {
            get {
                return ResourceManager.GetString("ContractCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Days.
        /// </summary>
        public static string ContractDays {
            get {
                return ResourceManager.GetString("ContractDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days 1.
        /// </summary>
        public static string Days1 {
            get {
                return ResourceManager.GetString("Days1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days 2.
        /// </summary>
        public static string Days2 {
            get {
                return ResourceManager.GetString("Days2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days 3.
        /// </summary>
        public static string Days3 {
            get {
                return ResourceManager.GetString("Days3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days 4.
        /// </summary>
        public static string Days4 {
            get {
                return ResourceManager.GetString("Days4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days 5.
        /// </summary>
        public static string Days5 {
            get {
                return ResourceManager.GetString("Days5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days cannot exceed 999999.
        /// </summary>
        public static string DaysExceed {
            get {
                return ResourceManager.GetString("DaysExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 1.
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 2.
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 3.
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 4.
        /// </summary>
        public static string Description4 {
            get {
                return ResourceManager.GetString("Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description 5.
        /// </summary>
        public static string Description5 {
            get {
                return ResourceManager.GetString("Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Days.
        /// </summary>
        public static string EffectiveDays {
            get {
                return ResourceManager.GetString("EffectiveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Days 1.
        /// </summary>
        public static string EffectiveDays1 {
            get {
                return ResourceManager.GetString("EffectiveDays1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Days 2.
        /// </summary>
        public static string EffectiveDays2 {
            get {
                return ResourceManager.GetString("EffectiveDays2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Days 3.
        /// </summary>
        public static string EffectiveDays3 {
            get {
                return ResourceManager.GetString("EffectiveDays3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Days 4.
        /// </summary>
        public static string EffectiveDays4 {
            get {
                return ResourceManager.GetString("EffectiveDays4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Days 5.
        /// </summary>
        public static string EffectiveDays5 {
            get {
                return ResourceManager.GetString("EffectiveDays5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the period line so that Lifetime Contract is false, Days is zero, and Description is empty will result in this period line being deleted.  Do you want to continue?.
        /// </summary>
        public static string EmptyPERIOD {
            get {
                return ResourceManager.GetString("EmptyPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/C Contract Codes.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime.
        /// </summary>
        public static string Expiry {
            get {
                return ResourceManager.GetString("Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Codes.
        /// </summary>
        public static string IC0800 {
            get {
                return ResourceManager.GetString("IC0800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime Contract 1.
        /// </summary>
        public static string LifetimeContract1 {
            get {
                return ResourceManager.GetString("LifetimeContract1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime Contract 2.
        /// </summary>
        public static string LifetimeContract2 {
            get {
                return ResourceManager.GetString("LifetimeContract2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime Contract 3.
        /// </summary>
        public static string LifetimeContract3 {
            get {
                return ResourceManager.GetString("LifetimeContract3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime Contract 4.
        /// </summary>
        public static string LifetimeContract4 {
            get {
                return ResourceManager.GetString("LifetimeContract4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime Contract 5.
        /// </summary>
        public static string LifetimeContract5 {
            get {
                return ResourceManager.GetString("LifetimeContract5", resourceCulture);
            }
        }
    }
}
