//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.IC.Resources.Process {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuarantineReleaseResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuarantineReleaseResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.IC.Resources.Process.QuarantineReleaseResx", typeof(QuarantineReleaseResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As at.
        /// </summary>
        public static string AsAt {
            get {
                return ResourceManager.GetString("AsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date entered lies outside the range specified in the company profile..
        /// </summary>
        public static string DateOutsideRange {
            get {
                return ResourceManager.GetString("DateOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/C Quarantine Release.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is not within known period..
        /// </summary>
        public static string FiscalyearNotExist {
            get {
                return ResourceManager.GetString("FiscalyearNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Item Number.
        /// </summary>
        public static string FromItemNumber {
            get {
                return ResourceManager.GetString("FromItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Lot Number.
        /// </summary>
        public static string FromLotNumber {
            get {
                return ResourceManager.GetString("FromLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Item Number.
        /// </summary>
        public static string ToItemNumber {
            get {
                return ResourceManager.GetString("ToItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Lot Number.
        /// </summary>
        public static string ToLotNumber {
            get {
                return ResourceManager.GetString("ToLotNumber", resourceCulture);
            }
        }
    }
}
