//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.OE.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreditDebitNotesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreditDebitNotesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.OE.Resources.Forms.CreditDebitNotesResx", typeof(CreditDebitNotesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/E Credit/Debit Notes.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to flag printed credit notes..
        /// </summary>
        public static string FlagnotupdatedCN {
            get {
                return ResourceManager.GetString("FlagnotupdatedCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to flag printed debit notes..
        /// </summary>
        public static string FlagnotupdatedDN {
            get {
                return ResourceManager.GetString("FlagnotupdatedDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Credit Note No..
        /// </summary>
        public static string FromCreditNoteNumber {
            get {
                return ResourceManager.GetString("FromCreditNoteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Debit Note No..
        /// </summary>
        public static string FromDebitNoteNumber {
            get {
                return ResourceManager.GetString("FromDebitNoteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Credit Notes Already Printed.
        /// </summary>
        public static string IncludeCNPrinted {
            get {
                return ResourceManager.GetString("IncludeCNPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Debit Notes Already Printed.
        /// </summary>
        public static string IncludeDNPrinted {
            get {
                return ResourceManager.GetString("IncludeDNPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Credit Note No..
        /// </summary>
        public static string ToCreditNoteNumber {
            get {
                return ResourceManager.GetString("ToCreditNoteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Debit Note No..
        /// </summary>
        public static string ToDebitNoteNumber {
            get {
                return ResourceManager.GetString("ToDebitNoteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Credit Note.
        /// </summary>
        public static string UseCreditNote {
            get {
                return ResourceManager.GetString("UseCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Debit Note.
        /// </summary>
        public static string UseDebitNote {
            get {
                return ResourceManager.GetString("UseDebitNote", resourceCulture);
            }
        }
    }
}
