//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.OE.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SalesPersonInquiryResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalesPersonInquiryResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.OE.Resources.Forms.SalesPersonInquiryResx", typeof(SalesPersonInquiryResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session date does not fall within one of the fiscal calendar periods. Defaulting to a fiscal calendar date..
        /// </summary>
        public static string BadSessionDateMessage {
            get {
                return ResourceManager.GetString("BadSessionDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details….
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Amount.
        /// </summary>
        public static string DocAmount {
            get {
                return ResourceManager.GetString("DocAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/E Salesperson Inquiry.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Calendar.
        /// </summary>
        public static string FiscalCalendar {
            get {
                return ResourceManager.GetString("FiscalCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Document Amount.
        /// </summary>
        public static string FunctionalDocumentAmount {
            get {
                return ResourceManager.GetString("FunctionalDocumentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid period..
        /// </summary>
        public static string InvPeriodMessage {
            get {
                return ResourceManager.GetString("InvPeriodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records are within the specified range of years/periods..
        /// </summary>
        public static string NoMatchYearPeriodMessage {
            get {
                return ResourceManager.GetString("NoMatchYearPeriodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a row..
        /// </summary>
        public static string NoSelectedListRowMessage {
            get {
                return ResourceManager.GetString("NoSelectedListRowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid period..
        /// </summary>
        public static string PeriodInvalid {
            get {
                return ResourceManager.GetString("PeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a valid period..
        /// </summary>
        public static string PeriodSelectionInvalid {
            get {
                return ResourceManager.GetString("PeriodSelectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Salesperson Name.
        /// </summary>
        public static string PrimarySalespersonName {
            get {
                return ResourceManager.GetString("PrimarySalespersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Document Amount.
        /// </summary>
        public static string SourceDocumentAmount {
            get {
                return ResourceManager.GetString("SourceDocumentAmount", resourceCulture);
            }
        }
    }
}
