//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.IC.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SlowMovingItemReportResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlowMovingItemReportResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.IC.Resources.Reports.SlowMovingItemReportResx", typeof(SlowMovingItemReportResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Days between Shipments Greater than.
        /// </summary>
        public static string AvgDays {
            get {
                return ResourceManager.GetString("AvgDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/C Slow Moving Items Report.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Items with.
        /// </summary>
        public static string IncludeItemswith {
            get {
                return ResourceManager.GetString("IncludeItemswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sales for More than.
        /// </summary>
        public static string NoSales {
            get {
                return ResourceManager.GetString("NoSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must define item segments before printing the Slow Moving Items Report..
        /// </summary>
        public static string NoSegments {
            get {
                return ResourceManager.GetString("NoSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period-To-Date (PTD) Turnover Less than.
        /// </summary>
        public static string PTD {
            get {
                return ResourceManager.GetString("PTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTD Units Sold Less than YTD Average by More than.
        /// </summary>
        public static string PTDLessYTDAbg {
            get {
                return ResourceManager.GetString("PTDLessYTDAbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one reporting option..
        /// </summary>
        public static string SelectAtleastOne {
            get {
                return ResourceManager.GetString("SelectAtleastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one reporting option..
        /// </summary>
        public static string SelectRptOpt {
            get {
                return ResourceManager.GetString("SelectRptOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year-To-Date (YTD) Turnover Less than.
        /// </summary>
        public static string YTD {
            get {
                return ResourceManager.GetString("YTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTD Units Sold Less than Last Year’s Average by More than.
        /// </summary>
        public static string YTDLessLastAvg {
            get {
                return ResourceManager.GetString("YTDLessLastAvg", resourceCulture);
            }
        }
    }
}
