//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.AR.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionalFieldsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionalFieldsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.AR.Resources.Forms.OptionalFieldsResx", typeof(OptionalFieldsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Blank.
        /// </summary>
        public static string AllowBlank {
            get {
                return ResourceManager.GetString("AllowBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Fields.
        /// </summary>
        public static string AR0500 {
            get {
                return ResourceManager.GetString("AR0500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field Locations.
        /// </summary>
        public static string AR0501 {
            get {
                return ResourceManager.GetString("AR0501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Insert.
        /// </summary>
        public static string AutoInsert {
            get {
                return ResourceManager.GetString("AutoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billings or Costs.
        /// </summary>
        public static string BillingsOrCosts {
            get {
                return ResourceManager.GetString("BillingsOrCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of Goods Sold.
        /// </summary>
        public static string CostofGoodsSold {
            get {
                return ResourceManager.GetString("CostofGoodsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers, National Accounts, and Customer Groups.
        /// </summary>
        public static string CustomersNationalAccountsandCustomerGroups {
            get {
                return ResourceManager.GetString("CustomersNationalAccountsandCustomerGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Value.
        /// </summary>
        public static string DateValue {
            get {
                return ResourceManager.GetString("DateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals.
        /// </summary>
        public static string Decimals {
            get {
                return ResourceManager.GetString("Decimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Amount Value.
        /// </summary>
        public static string DefaultAmountValue {
            get {
                return ResourceManager.GetString("DefaultAmountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Date Value.
        /// </summary>
        public static string DefaultDateValue {
            get {
                return ResourceManager.GetString("DefaultDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Integer Value.
        /// </summary>
        public static string DefaultIntegerValue {
            get {
                return ResourceManager.GetString("DefaultIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Number Value.
        /// </summary>
        public static string DefaultNumberValue {
            get {
                return ResourceManager.GetString("DefaultNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Text Value.
        /// </summary>
        public static string DefaultTextValue {
            get {
                return ResourceManager.GetString("DefaultTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Time Value.
        /// </summary>
        public static string DefaultTimeValue {
            get {
                return ResourceManager.GetString("DefaultTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value Description.
        /// </summary>
        public static string DefaultValueDescription {
            get {
                return ResourceManager.GetString("DefaultValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field {0} Default Value.
        /// </summary>
        public static string DefaultValueMessage {
            get {
                return ResourceManager.GetString("DefaultValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Yes/No Value.
        /// </summary>
        public static string DefaultYesOrNoValue {
            get {
                return ResourceManager.GetString("DefaultYesOrNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/R Optional Fields.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether this optional field is included with General Ledger transactions and with transactions sent to other subledgers..
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/L Accounts.
        /// </summary>
        public static string GLAccounts {
            get {
                return ResourceManager.GetString("GLAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Details.
        /// </summary>
        public static string InvoiceDetails {
            get {
                return ResourceManager.GetString("InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor.
        /// </summary>
        public static string Labor {
            get {
                return ResourceManager.GetString("Labor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Values.
        /// </summary>
        public static string NumberofValues {
            get {
                return ResourceManager.GetString("NumberofValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field.
        /// </summary>
        public static string OptionalField {
            get {
                return ResourceManager.GetString("OptionalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field Description.
        /// </summary>
        public static string OptionalFieldDesc {
            get {
                return ResourceManager.GetString("OptionalFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field Description.
        /// </summary>
        public static string OptionalFieldDescription {
            get {
                return ResourceManager.GetString("OptionalFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Fields For.
        /// </summary>
        public static string OptionalFieldsFor {
            get {
                return ResourceManager.GetString("OptionalFieldsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field Values.
        /// </summary>
        public static string OptionalFieldValues {
            get {
                return ResourceManager.GetString("OptionalFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhead.
        /// </summary>
        public static string Overhead {
            get {
                return ResourceManager.GetString("Overhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field Settings.
        /// </summary>
        public static string Settings1 {
            get {
                return ResourceManager.GetString("Settings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings determine whether this optional field is included with General Ledger transactions and with transactions sent to other subledgers..
        /// </summary>
        public static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-To Locations.
        /// </summary>
        public static string ShipToLocations {
            get {
                return ResourceManager.GetString("ShipToLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typed Default Value Field Index.
        /// </summary>
        public static string TypedDefaultValueFieldIndex {
            get {
                return ResourceManager.GetString("TypedDefaultValueFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typed Value Field Index.
        /// </summary>
        public static string TypedValueFieldIndex {
            get {
                return ResourceManager.GetString("TypedValueFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string ValueDefault {
            get {
                return ResourceManager.GetString("ValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Description.
        /// </summary>
        public static string ValueDesc {
            get {
                return ResourceManager.GetString("ValueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Set.
        /// </summary>
        public static string ValueSet {
            get {
                return ResourceManager.GetString("ValueSet", resourceCulture);
            }
        }
    }
}
