//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.CA.SBS.ERP.Sage300.OE.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceEntryResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceEntryResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.CA.SBS.ERP.Sage300.OE.Resources.Forms.InvoiceEntryResx", typeof(InvoiceEntryResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Partial Shipments.
        /// </summary>
        public static string Allowpartialshipments {
            get {
                return ResourceManager.GetString("Allowpartialshipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number cannot be blank.
        /// </summary>
        public static string BlankInvoiceNumberMsg {
            get {
                return ResourceManager.GetString("BlankInvoiceNumberMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/Tax.
        /// </summary>
        public static string BtnItemTax {
            get {
                return ResourceManager.GetString("BtnItemTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments/Instructions.
        /// </summary>
        public static string CommentsInstructions {
            get {
                return ResourceManager.GetString("CommentsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments/Instructions Type.
        /// </summary>
        public static string CommentsInstructionsType {
            get {
                return ResourceManager.GetString("CommentsInstructionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete invoice %1?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Invoice from Shipments.
        /// </summary>
        public static string CreateInvoiceFromShipments {
            get {
                return ResourceManager.GetString("CreateInvoiceFromShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        public static string CurrencyRate {
            get {
                return ResourceManager.GetString("CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Discount Level.
        /// </summary>
        public static string CustomerDiscountLevel {
            get {
                return ResourceManager.GetString("CustomerDiscountLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting Date.
        /// </summary>
        public static string DateBus {
            get {
                return ResourceManager.GetString("DateBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Number.
        /// </summary>
        public static string DetailNumber {
            get {
                return ResourceManager.GetString("DetailNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Discount Base With Tax.
        /// </summary>
        public static string DocumentDiscountBaseWithTax {
            get {
                return ResourceManager.GetString("DocumentDiscountBaseWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Discount Base w/o Tax.
        /// </summary>
        public static string DocumentDiscountBasewoTax {
            get {
                return ResourceManager.GetString("DocumentDiscountBasewoTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dos Convert.
        /// </summary>
        public static string DosConvert {
            get {
                return ResourceManager.GetString("DosConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered By.
        /// </summary>
        public static string EnteredBy {
            get {
                return ResourceManager.GetString("EnteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/E Invoice Entry.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exclude this shipment from the invoice?.
        /// </summary>
        public static string ExcludeShipFromInvoice {
            get {
                return ResourceManager.GetString("ExcludeShipFromInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Price.
        /// </summary>
        public static string ExtendedPrice {
            get {
                return ResourceManager.GetString("ExtendedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Tax Calculation.
        /// </summary>
        public static string ForceTaxCalculation {
            get {
                return ResourceManager.GetString("ForceTaxCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free On Board Point.
        /// </summary>
        public static string FreeOnBoardPoint {
            get {
                return ResourceManager.GetString("FreeOnBoardPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items/Taxes - O/E Invoice Entry.
        /// </summary>
        public static string FrmDetailZoom {
            get {
                return ResourceManager.GetString("FrmDetailZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From How Many Shipments.
        /// </summary>
        public static string FromHowManyShipments {
            get {
                return ResourceManager.GetString("FromHowManyShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Multiple Shipments.
        /// </summary>
        public static string FromMultipleShipments {
            get {
                return ResourceManager.GetString("FromMultipleShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate From Multiple Shipments.
        /// </summary>
        public static string GenerateFromMultipleShipments {
            get {
                return ResourceManager.GetString("GenerateFromMultipleShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice From Multipal Ships.
        /// </summary>
        public static string GenerateInvFromMultShips {
            get {
                return ResourceManager.GetString("GenerateInvFromMultShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice From Single Ship.
        /// </summary>
        public static string GenerateInvFromSingleShip {
            get {
                return ResourceManager.GetString("GenerateInvFromSingleShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Calculate Tax.
        /// </summary>
        public static string GOCALCTAX {
            get {
                return ResourceManager.GetString("GOCALCTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Retainage.
        /// </summary>
        public static string HasRetainage {
            get {
                return ResourceManager.GetString("HasRetainage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Comments/Instructions.
        /// </summary>
        public static string HaveCommentsInstructions {
            get {
                return ResourceManager.GetString("HaveCommentsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/C Day End Trans. Number.
        /// </summary>
        public static string ICDayEndTransNumber {
            get {
                return ResourceManager.GetString("ICDayEndTransNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number does not exist..
        /// </summary>
        public static string InvalidInvoiceNumber {
            get {
                return ResourceManager.GetString("InvalidInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment number %1 does not exist..
        /// </summary>
        public static string InvalidShipmentNumber {
            get {
                return ResourceManager.GetString("InvalidShipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amount Due.
        /// </summary>
        public static string InvoiceAmountDue {
            get {
                return ResourceManager.GetString("InvoiceAmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Details.
        /// </summary>
        public static string InvoiceDetails {
            get {
                return ResourceManager.GetString("InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Discount on Misc. Charges.
        /// </summary>
        public static string InvoiceDisconMiscCharges {
            get {
                return ResourceManager.GetString("InvoiceDisconMiscCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Discount Amount.
        /// </summary>
        public static string InvoiceDiscountAmount {
            get {
                return ResourceManager.GetString("InvoiceDiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Discount Amount Override.
        /// </summary>
        public static string InvoiceDiscountAmountOverride {
            get {
                return ResourceManager.GetString("InvoiceDiscountAmountOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Discount Base.
        /// </summary>
        public static string InvoiceDiscountBase {
            get {
                return ResourceManager.GetString("InvoiceDiscountBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Discount Percentage.
        /// </summary>
        public static string InvoiceDiscountPercentage {
            get {
                return ResourceManager.GetString("InvoiceDiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/E Invoice Detail Optional Fields.
        /// </summary>
        public static string InvoiceDtlOptFlds {
            get {
                return ResourceManager.GetString("InvoiceDtlOptFlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Excluded Tax Total Amount.
        /// </summary>
        public static string InvoiceExcludedTaxTotAmount {
            get {
                return ResourceManager.GetString("InvoiceExcludedTaxTotAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Fiscal Period.
        /// </summary>
        public static string InvoiceFiscalPeriod {
            get {
                return ResourceManager.GetString("InvoiceFiscalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Fiscal Year.
        /// </summary>
        public static string InvoiceFiscalYear {
            get {
                return ResourceManager.GetString("InvoiceFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Included Tax Total Amount.
        /// </summary>
        public static string InvoiceIncludedTaxTotalAmount {
            get {
                return ResourceManager.GetString("InvoiceIncludedTaxTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Item Total Amount.
        /// </summary>
        public static string InvoiceItemTotalAmount {
            get {
                return ResourceManager.GetString("InvoiceItemTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice will reduce the item quantity in this location below zero.  Do you want to proceed?.
        /// </summary>
        public static string InvoiceNegInventory {
            get {
                return ResourceManager.GetString("InvoiceNegInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice will reduce the item quantity in this location for at least one of the components below zero. Do you want to proceed?.
        /// </summary>
        public static string InvoiceNegInventoryForKit {
            get {
                return ResourceManager.GetString("InvoiceNegInventoryForKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percent must be less than or equal to 100%..
        /// </summary>
        public static string InvoiceNoMoreThan100DiscountPercent {
            get {
                return ResourceManager.GetString("InvoiceNoMoreThan100DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percent cannot be negative..
        /// </summary>
        public static string InvoiceNoNegativeDiscountPercent {
            get {
                return ResourceManager.GetString("InvoiceNoNegativeDiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice does not exist..
        /// </summary>
        public static string InvoiceNotExist {
            get {
                return ResourceManager.GetString("InvoiceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Payment Discount.
        /// </summary>
        public static string InvoicePaymentDiscount {
            get {
                return ResourceManager.GetString("InvoicePaymentDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Payment in Customer Currency.
        /// </summary>
        public static string InvoicePaymntInCustomerCurr {
            get {
                return ResourceManager.GetString("InvoicePaymntInCustomerCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Printed.
        /// </summary>
        public static string InvoicePrinted {
            get {
                return ResourceManager.GetString("InvoicePrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Running Total.
        /// </summary>
        public static string InvoiceRunningTotal {
            get {
                return ResourceManager.GetString("InvoiceRunningTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Status.
        /// </summary>
        public static string InvoiceStatus {
            get {
                return ResourceManager.GetString("InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Subtotal Amount.
        /// </summary>
        public static string InvoiceSubtotalAmount {
            get {
                return ResourceManager.GetString("InvoiceSubtotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Total Before Tax.
        /// </summary>
        public static string InvoiceTotalBeforeTax {
            get {
                return ResourceManager.GetString("InvoiceTotalBeforeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Total Estimated Weight.
        /// </summary>
        public static string InvoiceTotalEstimatedWeight {
            get {
                return ResourceManager.GetString("InvoiceTotalEstimatedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Total Misc. Charges.
        /// </summary>
        public static string InvoiceTotalMiscCharges {
            get {
                return ResourceManager.GetString("InvoiceTotalMiscCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Total With Invoice Discount.
        /// </summary>
        public static string InvoiceTotalWithInvoiceDisc {
            get {
                return ResourceManager.GetString("InvoiceTotalWithInvoiceDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Total With Tax.
        /// </summary>
        public static string InvoiceTotalWithTax {
            get {
                return ResourceManager.GetString("InvoiceTotalWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Uniquifier.
        /// </summary>
        public static string InvoiceUniquifier {
            get {
                return ResourceManager.GetString("InvoiceUniquifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Weight UOM.
        /// </summary>
        public static string InvoiceWeightUOM {
            get {
                return ResourceManager.GetString("InvoiceWeightUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting failed. You must enter the invoice again..
        /// </summary>
        public static string InvPostingFailed {
            get {
                return ResourceManager.GetString("InvPostingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Account Set.
        /// </summary>
        public static string ItemAccountSet {
            get {
                return ResourceManager.GetString("ItemAccountSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Pricing.
        /// </summary>
        public static string ItemPricing {
            get {
                return ResourceManager.GetString("ItemPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Tax Class.
        /// </summary>
        public static string ItemTaxClass {
            get {
                return ResourceManager.GetString("ItemTaxClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Related.
        /// </summary>
        public static string JobRelated {
            get {
                return ResourceManager.GetString("JobRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Uniquifier.
        /// </summary>
        public static string LineUniquifier {
            get {
                return ResourceManager.GetString("LineUniquifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Description.
        /// </summary>
        public static string LocationCodeDescription {
            get {
                return ResourceManager.GetString("LocationCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Charges.
        /// </summary>
        public static string MiscCharges {
            get {
                return ResourceManager.GetString("MiscCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Invoice From Shipments.
        /// </summary>
        public static string MultipleShipments {
            get {
                return ResourceManager.GetString("MultipleShipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Labels.
        /// </summary>
        public static string NumberOfLabels {
            get {
                return ResourceManager.GetString("NumberOfLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Lines in Invoice.
        /// </summary>
        public static string NumberOfLinesInInvoice {
            get {
                return ResourceManager.GetString("NumberOfLinesInInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Terms Payments.
        /// </summary>
        public static string NumberOfTermsPayments {
            get {
                return ResourceManager.GetString("NumberOfTermsPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Comments Instructions.
        /// </summary>
        public static string OE0160 {
            get {
                return ResourceManager.GetString("OE0160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Details.
        /// </summary>
        public static string OE0400 {
            get {
                return ResourceManager.GetString("OE0400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Detail Optional Fields.
        /// </summary>
        public static string OE0401 {
            get {
                return ResourceManager.GetString("OE0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Detail Lot Numbers.
        /// </summary>
        public static string OE0406 {
            get {
                return ResourceManager.GetString("OE0406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Detail Serial Numbers.
        /// </summary>
        public static string OE0407 {
            get {
                return ResourceManager.GetString("OE0407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string OE0420 {
            get {
                return ResourceManager.GetString("OE0420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Optional Fields.
        /// </summary>
        public static string OE0422 {
            get {
                return ResourceManager.GetString("OE0422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Shipments to Invoice.
        /// </summary>
        public static string OE0427 {
            get {
                return ResourceManager.GetString("OE0427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Payment Schedules.
        /// </summary>
        public static string OE0720 {
            get {
                return ResourceManager.GetString("OE0720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OE Pending Balance.
        /// </summary>
        public static string OEPendingBalance {
            get {
                return ResourceManager.GetString("OEPendingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/E Invoice Prepayments.
        /// </summary>
        public static string OEPrepayments {
            get {
                return ResourceManager.GetString("OEPrepayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discountable.
        /// </summary>
        public static string PaymentDiscountable {
            get {
                return ResourceManager.GetString("PaymentDiscountable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Home Currency Description.
        /// </summary>
        public static string PaymentHomeCurrencyDesc {
            get {
                return ResourceManager.GetString("PaymentHomeCurrencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Rate Type Description.
        /// </summary>
        public static string PaymentRateTypeDescription {
            get {
                return ResourceManager.GetString("PaymentRateTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Schedules.
        /// </summary>
        public static string PaymentSchedules {
            get {
                return ResourceManager.GetString("PaymentSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Source Currency Description.
        /// </summary>
        public static string PaymentSourceCurrencyDesc {
            get {
                return ResourceManager.GetString("PaymentSourceCurrencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Credit Limit Check.
        /// </summary>
        public static string PerformCreditLimitCheck {
            get {
                return ResourceManager.GetString("PerformCreditLimitCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string POSTDATE {
            get {
                return ResourceManager.GetString("POSTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting completed. Invoice Number: {0}. Do you want to print the invoice?.
        /// </summary>
        public static string PostDone {
            get {
                return ResourceManager.GetString("PostDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting completed. Invoice Number: {0}..
        /// </summary>
        public static string PostDoneNoPrint {
            get {
                return ResourceManager.GetString("PostDoneNoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting failed. A credit card payment has already been processed in Sage Payment Solutions for this invoice. Sign in to Sage Virtual Terminal to review transaction status..
        /// </summary>
        public static string PostingFailedWithSPSCharge {
            get {
                return ResourceManager.GetString("PostingFailedWithSPSCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Auth Exists For Invoice.
        /// </summary>
        public static string PreAuthExistsForInvoice {
            get {
                return ResourceManager.GetString("PreAuthExistsForInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Apply To.
        /// </summary>
        public static string PrepaymentApplyTo {
            get {
                return ResourceManager.GetString("PrepaymentApplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Bank Code.
        /// </summary>
        public static string PrepaymentBankCode {
            get {
                return ResourceManager.GetString("PrepaymentBankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Batch Number.
        /// </summary>
        public static string PrepaymentBatchNumber {
            get {
                return ResourceManager.GetString("PrepaymentBatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Check Date.
        /// </summary>
        public static string PrepaymentCheckDate {
            get {
                return ResourceManager.GetString("PrepaymentCheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Check Number.
        /// </summary>
        public static string PrepaymentCheckNumber {
            get {
                return ResourceManager.GetString("PrepaymentCheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Date Match.
        /// </summary>
        public static string PrepaymentDateMatch {
            get {
                return ResourceManager.GetString("PrepaymentDateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Fiscal Period.
        /// </summary>
        public static string PrepaymentFiscalPeriod {
            get {
                return ResourceManager.GetString("PrepaymentFiscalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Fiscal Year.
        /// </summary>
        public static string PrepaymentFiscalYear {
            get {
                return ResourceManager.GetString("PrepaymentFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Home Currency.
        /// </summary>
        public static string PrepaymentHomeCurrency {
            get {
                return ResourceManager.GetString("PrepaymentHomeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment in Bank Currency.
        /// </summary>
        public static string PrepaymentInBankCurrency {
            get {
                return ResourceManager.GetString("PrepaymentInBankCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Rate.
        /// </summary>
        public static string PrepaymentRate {
            get {
                return ResourceManager.GetString("PrepaymentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Rate Date.
        /// </summary>
        public static string PrepaymentRateDate {
            get {
                return ResourceManager.GetString("PrepaymentRateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Rate Operator.
        /// </summary>
        public static string PrepaymentRateOperator {
            get {
                return ResourceManager.GetString("PrepaymentRateOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Rate Type.
        /// </summary>
        public static string PrepaymentRateType {
            get {
                return ResourceManager.GetString("PrepaymentRateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Receipt Type.
        /// </summary>
        public static string PrepaymentReceiptType {
            get {
                return ResourceManager.GetString("PrepaymentReceiptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Source Currency.
        /// </summary>
        public static string PrepaymentSourceCurrency {
            get {
                return ResourceManager.GetString("PrepaymentSourceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment Spread.
        /// </summary>
        public static string PrepaymentSpread {
            get {
                return ResourceManager.GetString("PrepaymentSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Approved By.
        /// </summary>
        public static string PriceApprovedBy {
            get {
                return ResourceManager.GetString("PriceApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List Code.
        /// </summary>
        public static string PriceListCode {
            get {
                return ResourceManager.GetString("PriceListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List Description.
        /// </summary>
        public static string PriceListCodeDescription {
            get {
                return ResourceManager.GetString("PriceListCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Unit Price.
        /// </summary>
        public static string PricingUnitPrice {
            get {
                return ResourceManager.GetString("PricingUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process OE Command.
        /// </summary>
        public static string ProcessOECommand {
            get {
                return ResourceManager.GetString("ProcessOECommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process OIP Command.
        /// </summary>
        public static string ProcessOIPCommand {
            get {
                return ResourceManager.GetString("ProcessOIPCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type Description.
        /// </summary>
        public static string RateTypeDescription {
            get {
                return ResourceManager.GetString("RateTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Multi Payment Dates.
        /// </summary>
        public static string RecalcMultiPaymentDates {
            get {
                return ResourceManager.GetString("RecalcMultiPaymentDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Tax.
        /// </summary>
        public static string RECALCTAX {
            get {
                return ResourceManager.GetString("RECALCTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace the invoice information you entered with the information from shipment {0}?.
        /// </summary>
        public static string ReplaceInvoiceDetails {
            get {
                return ResourceManager.GetString("ReplaceInvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Shipping Labels.
        /// </summary>
        public static string RequiresShippingLabels {
            get {
                return ResourceManager.GetString("RequiresShippingLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retainage Exchange Rate.
        /// </summary>
        public static string RetainageExchangeRate {
            get {
                return ResourceManager.GetString("RetainageExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to post this invoice?.
        /// </summary>
        public static string SaveInvoice {
            get {
                return ResourceManager.GetString("SaveInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment No..
        /// </summary>
        public static string ShipmentNo {
            get {
                return ResourceManager.GetString("ShipmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment number {0} does not exist..
        /// </summary>
        public static string ShipmentNoDoesNotExistsErrorMsg {
            get {
                return ResourceManager.GetString("ShipmentNoDoesNotExistsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Payments Total.
        /// </summary>
        public static string ShipmentPaymentsTotal {
            get {
                return ResourceManager.GetString("ShipmentPaymentsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Labels Printed.
        /// </summary>
        public static string ShippingLabelsPrinted {
            get {
                return ResourceManager.GetString("ShippingLabelsPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship-Via Code.
        /// </summary>
        public static string ShipViaCode {
            get {
                return ResourceManager.GetString("ShipViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ShipViaCodeDescription {
            get {
                return ResourceManager.GetString("ShipViaCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authority 1 Description.
        /// </summary>
        public static string TaxAuthority1Description {
            get {
                return ResourceManager.GetString("TaxAuthority1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authority 2 Description.
        /// </summary>
        public static string TaxAuthority2Description {
            get {
                return ResourceManager.GetString("TaxAuthority2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authority 3 Description.
        /// </summary>
        public static string TaxAuthority3Description {
            get {
                return ResourceManager.GetString("TaxAuthority3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authority 4 Description.
        /// </summary>
        public static string TaxAuthority4Description {
            get {
                return ResourceManager.GetString("TaxAuthority4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authority 5 Description.
        /// </summary>
        public static string TaxAuthority5Description {
            get {
                return ResourceManager.GetString("TaxAuthority5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer or item tax class is not valid for this invoice..
        /// </summary>
        public static string TaxCalculation {
            get {
                return ResourceManager.GetString("TaxCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Group Description.
        /// </summary>
        public static string TaxGroupCodeDescription {
            get {
                return ResourceManager.GetString("TaxGroupCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Reporting Currency.
        /// </summary>
        public static string TaxReportingCurrency {
            get {
                return ResourceManager.GetString("TaxReportingCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Reporting Currency Description.
        /// </summary>
        public static string TaxReportingCurrencyDescription {
            get {
                return ResourceManager.GetString("TaxReportingCurrencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Reporting Currency Invoice Exchange Rate.
        /// </summary>
        public static string TaxReportingCurrInvoiceExchangeRate {
            get {
                return ResourceManager.GetString("TaxReportingCurrInvoiceExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Reporting Currency Shipment Exchange Rate.
        /// </summary>
        public static string TaxReportingCurrShipmentExchangeRate {
            get {
                return ResourceManager.GetString("TaxReportingCurrShipmentExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Reporting Shipment TR Currency.
        /// </summary>
        public static string TaxReportingShipmentTRCurr {
            get {
                return ResourceManager.GetString("TaxReportingShipmentTRCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Version.
        /// </summary>
        public static string TaxVersion {
            get {
                return ResourceManager.GetString("TaxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Payments As Of Date.
        /// </summary>
        public static string TermsPaymentsAsOfDate {
            get {
                return ResourceManager.GetString("TermsPaymentsAsOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Rate Override.
        /// </summary>
        public static string TermsRateOverride {
            get {
                return ResourceManager.GetString("TermsRateOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Terms Amount Due.
        /// </summary>
        public static string TotalTermsAmountDue {
            get {
                return ResourceManager.GetString("TotalTermsAmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Currency Description.
        /// </summary>
        public static string TRShipmentCurrencyDescription {
            get {
                return ResourceManager.GetString("TRShipmentCurrencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Rate.
        /// </summary>
        public static string TRShipmentRate {
            get {
                return ResourceManager.GetString("TRShipmentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Rate Date.
        /// </summary>
        public static string TRShipmentRateDate {
            get {
                return ResourceManager.GetString("TRShipmentRateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Rate Date Matching.
        /// </summary>
        public static string TRShipmentRateDateMatching {
            get {
                return ResourceManager.GetString("TRShipmentRateDateMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Rate Operator.
        /// </summary>
        public static string TRShipmentRateOperator {
            get {
                return ResourceManager.GetString("TRShipmentRateOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Rate Override Flag.
        /// </summary>
        public static string TRShipmentRateOverrideFlag {
            get {
                return ResourceManager.GetString("TRShipmentRateOverrideFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Rate Type.
        /// </summary>
        public static string TRShipmentRateType {
            get {
                return ResourceManager.GetString("TRShipmentRateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Rate Type Description.
        /// </summary>
        public static string TRShipmentRateTypeDescription {
            get {
                return ResourceManager.GetString("TRShipmentRateTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR Shipment Spread.
        /// </summary>
        public static string TRShipmentSpread {
            get {
                return ResourceManager.GetString("TRShipmentSpread", resourceCulture);
            }
        }
    }
}
