// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.Templates.Flat.Script
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Behaviour : BehaviourBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* The MIT License (MIT) */ 
            
            #line default
            #line hidden
            
            #line 2 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* Copyright (c) 1994-2019 The Sage Group plc or its licensors.  All rights reserved. */ 
            
            #line default
            #line hidden
            
            #line 3 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* */ 
            
            #line default
            #line hidden
            
            #line 4 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* Permission is hereby granted, free of charge, to any person obtaining a copy of */ 
            
            #line default
            #line hidden
            
            #line 5 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* this software and associated documentation files (the "Software"), to deal in */ 
            
            #line default
            #line hidden
            
            #line 6 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* the Software without restriction, including without limitation the rights to use, */ 
            
            #line default
            #line hidden
            
            #line 7 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the */ 
            
            #line default
            #line hidden
            
            #line 8 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* Software, and to permit persons to whom the Software is furnished to do so, */ 
            
            #line default
            #line hidden
            
            #line 9 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* subject to the following conditions: */ 
            
            #line default
            #line hidden
            
            #line 10 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* */ 
            
            #line default
            #line hidden
            
            #line 11 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* The above copyright notice and this permission notice shall be included in all */ 
            
            #line default
            #line hidden
            
            #line 12 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* copies or substantial portions of the Software. */ 
            
            #line default
            #line hidden
            
            #line 13 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* */ 
            
            #line default
            #line hidden
            
            #line 14 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, */ 
            
            #line default
            #line hidden
            
            #line 15 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A */ 
            
            #line default
            #line hidden
            
            #line 16 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT */ 
            
            #line default
            #line hidden
            
            #line 17 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF */ 
            
            #line default
            #line hidden
            
            #line 18 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE */ 
            
            #line default
            #line hidden
            
            #line 19 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
 /* OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */ 
            
            #line default
            #line hidden
            
            #line 24 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"

    // Locals
    var entityName = view.Properties[BusinessView.Constants.EntityName];
    var localEntityName = entityName.Substring(0, 1).ToLower() + entityName.Substring(1);
    var containerName = entityName; 
    var moduleId = view.Properties[BusinessView.Constants.ModuleId];
    var copyright = settings.Copyright;
    var keyFieldName = view.Keys.Count > 0 ? view.Keys.First() : entityName;
    var localKeyFieldName = keyFieldName.Substring(0, 1).ToLower() + keyFieldName.Substring(1);

    var xmlLayout = settings.XmlLayout;
    var widgets = settings.Widgets;
    var ignoredProperties = string.Empty;

    // Build list of ignored properties
    // Iterate XML, if any
    if (xmlLayout != null)
    {
        // Iterate date widgets, if any
        if (widgets.ContainsKey("DateTime"))
        {
            foreach (var widget in widgets["DateTime"])
            {
                ignoredProperties += ", \"Is" + widget + "Disabled\"";
            }
        }
    }


            
            #line default
            #line hidden
            this.Write("/* ");
            
            #line 53 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(copyright));
            
            #line default
            #line hidden
            this.Write(" */\r\n\r\n// Add the following commented line to enable TypeScript static type check" +
                    "ing\r\n// Remove this line if not needed\r\n//@ts-check\r\n\r\n\"use strict\";\r\n\r\nvar mode" +
                    "lData;\r\nvar ");
            
            #line 62 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI = ");
            
            #line 62 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI || {};\r\n\r\n");
            
            #line 64 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI = {\r\n    ");
            
            #line 65 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model: {},\r\n    ignoreIsDirtyProperties: [\"");
            
            #line 66 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 66 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ignoredProperties));
            
            #line default
            #line hidden
            this.Write("],\r\n    computedProperties: [\"UIMode\"],\r\n    hasKoBindingApplied: false,\r\n    isK" +
                    "endoControlNotInitialised: false,\r\n    ");
            
            #line 70 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(": null,\r\n\r\n\t/**\r\n     * Initialization\r\n\t *\r\n\t * @method init\r\n\t */\r\n    init: fu" +
                    "nction () {\r\n    ");
            
            #line 78 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.initButtons();\r\n    ");
            
            #line 79 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.initFinders();\r\n    ");
            
            #line 80 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.initTextboxes();\r\n    ");
            
            #line 81 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.initialLoad(");
            
            #line 81 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n    ");
            
            #line 82 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.setkey();\r\n    },\r\n\r\n\t/**\r\n     * Save\r\n\t *\r\n\t * @method save");
            
            #line 88 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write("\r\n\t */\r\n    save");
            
            #line 90 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write(": function () {\r\n        if ($(\"#frm");
            
            #line 91 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("\").valid()) {\r\n            var data = sg.utls.ko.toJS(modelData, ");
            
            #line 92 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.computedProperties);\r\n            if (modelData.UIMode() === sg.utls.Operation" +
                    "Mode.SAVE) {\r\n                ");
            
            #line 94 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Repository.update(data, ");
            
            #line 94 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.update);\r\n            } else {\r\n                ");
            
            #line 96 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Repository.add(data, ");
            
            #line 96 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.update);\r\n            }\r\n        }\r\n    },\r\n\r\n\t/**\r\n     * Initialize t" +
                    "he Buttons\r\n\t *\r\n\t * @method initButtons\r\n\t */\r\n    initButtons: function () {\r\n" +
                    "        // Import/Export Buttons\r\n        sg.exportHelper.setExportEvent(\"btnOpt" +
                    "ionExport\", \"");
            
            #line 108 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(moduleId.ToLower()));
            
            #line default
            #line hidden
            
            #line 108 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\", false, $.noop);\r\n        sg.importHelper.setImportEvent(\"btnOptionImport\", \"");
            
            #line 109 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(moduleId.ToLower()));
            
            #line default
            #line hidden
            
            #line 109 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\", false, $.noop);\r\n\r\n        // Key field change event\r\n        $(\"#txt");
            
            #line 112 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("\").on(\'blur\', function (e) {\r\n            modelData.");
            
            #line 113 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("($(\"#txt");
            
            #line 113 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("\").val());\r\n            if (sg.controls.GetString(modelData.");
            
            #line 114 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("()) !== \"\") {\r\n                ");
            
            #line 115 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.checkIsDirty(");
            
            #line 115 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.get, ");
            
            #line 115 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 115 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(");\r\n            }\r\n        });\r\n\r\n        // Create New Button\r\n        $(\"#btnNe" +
                    "w\").on(\'click\', function () {\r\n            ");
            
            #line 121 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.checkIsDirty(");
            
            #line 121 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.create, ");
            
            #line 121 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 121 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(");\r\n        });\r\n\r\n        // Save Button\r\n        $(\"#btnSave\").on(\'click\', func" +
                    "tion () {\r\n            sg.utls.SyncExecute(");
            
            #line 126 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.save");
            
            #line 126 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityName));
            
            #line default
            #line hidden
            this.Write(");\r\n        });\r\n\r\n        // Delete Button\r\n        $(\"#btnDelete\").on(\'click\', " +
                    "function () {\r\n            if ($(\"#frm");
            
            #line 131 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("\").valid()) {\r\n                var message = jQuery.validator.format(");
            
            #line 132 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Resources.DeleteConfirmMessage, ");
            
            #line 132 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Resources.");
            
            #line 132 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("Title, modelData.");
            
            #line 132 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("());\r\n                sg.utls.showKendoConfirmationDialog(function () {\r\n        " +
                    "            sg.utls.clearValidations(\"frm");
            
            #line 134 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    ");
            
            #line 135 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Repository.delete(modelData.");
            
            #line 135 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("(), ");
            
            #line 135 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.delete);\r\n                }, null, message, ");
            
            #line 136 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Resources.DeleteTitle);\r\n            }\r\n        });\r\n    },\r\n\r\n\t/**\r\n     * Initi" +
                    "alize the Drop Down Widgets, if any\r\n\t *\r\n\t * @method initDropDownList\r\n\t */\r\n  " +
                    "  initDropDownList: function () {\r\n    ");
            
            #line 147 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"

        // Iterate XML, if any
        if (xmlLayout != null)
        {
            // Iterate drop down widgets, if any
            if (widgets.ContainsKey("Dropdown"))
            {
                foreach (var widget in widgets["Dropdown"])
                {
                    WriteLine(new string(' ', 8) + "sg.utls.kndoUI.dropDownList(\"ddl" + widget + "\");");
                }
            }
        }
    
            
            #line default
            #line hidden
            this.Write("    },\r\n\r\n\t/**\r\n     * Initialize the Finders, if any\r\n\t *\r\n\t * @method initFinde" +
                    "rs\r\n\t */\r\n    initFinders: function () {\r\n            sg.viewFinderHelper.setVie" +
                    "wFinder(\"btnFinder");
            
            #line 169 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("\", \"txt");
            
            #line 169 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("\",");
            
            #line 169 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
        
        Write("/*TODO Modify the finder property*/ {{viewID:\"{0}\", ", view.Properties[BusinessView.Constants.ViewId]);
        Write("viewOrder:0, displayFieldNames:[");
        
        for( int i=0; i < view.Fields.Count() && i < 4; i++)
        {
            if (i > 0)
                Write(", ");

            Write("\"{0}\"", view.Fields[i].ServerFieldName);
         }
        Write("], returnFieldNames:[\"{0}\"],", view.Fields[0].ServerFieldName);
        WriteLine("filter:null, initKeyValues:[], parentValAsInitKey:true});");

            
            #line default
            #line hidden
            this.Write("    },\r\n\r\n        /**\r\n     * Initialize the Textboxes, if any\r\n\t *\r\n\t * @method " +
                    "initTextboxes\r\n    */\r\n    initTextboxes: function () {\r\n    ");
            
            #line 191 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"

        // Init date widgets, if any
        // Iterate XML, if any
        if (xmlLayout != null)
        {
            // Iterate date widgets, if any
            if (widgets.ContainsKey("DateTime"))
            {
                foreach (var widget in widgets["DateTime"])
                {
                    WriteLine(new string(' ', 4) + "$(\"#txt" + widget + "\").on('change', function(e) {");
                    WriteLine(new string(' ', 8) + "if (sg.utls.kndoUI.checkForValidDate($(\"#txt" + widget + "\").val())) {");
                    WriteLine(new string(' ', 12) + "sg.utls.clearValidations(\"frm" + containerName + "\");");
                    WriteLine(new string(' ', 8) + "} else {");
                    WriteLine(new string(' ', 12) + "sg.controls.Focus($(\"#txt" + widget + "\"));");
                    WriteLine(new string(' ', 8) + "}");
                    WriteLine(new string(' ', 4) + "});");
                    WriteLine("");
                }
            }
        }
    
            
            #line default
            #line hidden
            this.Write("    },\r\n\r\n\t/**\r\n     * Get\r\n\t *\r\n\t * @method get\r\n\t */\r\n    get: function () {\r\n " +
                    "       ");
            
            #line 221 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Repository.get(modelData.");
            
            #line 221 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("(), ");
            
            #line 221 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.get);\r\n    },\r\n\r\n\t/**\r\n     * Create\r\n\t *\r\n\t * @method create\r\n\t */\r\n  " +
                    "  create: function () {\r\n        sg.utls.clearValidations(\"frm");
            
            #line 230 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("\");\r\n        ");
            
            #line 231 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Repository.create(");
            
            #line 231 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.create);\r\n    },\r\n\r\n\t/**\r\n     * Is Dirty check\r\n\t *\r\n\t * @method check" +
                    "IsDirty\r\n     * @param functionToCall\r\n     * @param ");
            
            #line 239 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write("\r\n\t */\r\n    checkIsDirty: function (functionToCall, ");
            
            #line 241 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(") {\r\n        if (");
            
            #line 242 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 242 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model.isModelDirty.isDirty() && ");
            
            #line 242 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(" != null && ");
            
            #line 242 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(" != \"\") {\r\n            sg.utls.showKendoConfirmationDialog(\r\n                func" +
                    "tion () { // Yes\r\n                    sg.utls.clearValidations(\"frm");
            
            #line 245 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(containerName));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    functionToCall.call();\r\n                },\r\n            " +
                    "    function () { // No\r\n                    if (sg.controls.GetString(");
            
            #line 249 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(") != sg.controls.GetString(modelData.");
            
            #line 249 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("())) {\r\n                        modelData.");
            
            #line 250 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 250 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(");\r\n                   }\r\n                   return;\r\n                },\r\n       " +
                    "         jQuery.validator.format(globalResource.SaveConfirm, ");
            
            #line 254 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Resources.");
            
            #line 254 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("Title, ");
            
            #line 254 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write("));\r\n        } else {\r\n            functionToCall.call();\r\n        }\r\n    }\r\n};\r\n" +
                    "\r\n// Callbacks\r\nvar ");
            
            #line 262 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess = {\r\n\r\n\t/**\r\n     * Setkey\r\n\t *\r\n\t * @method setkey\r\n\t */\r\n    setkey: " +
                    "function () {\r\n        ");
            
            #line 270 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 270 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localKeyFieldName));
            
            #line default
            #line hidden
            this.Write(" = modelData.");
            
            #line 270 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("();\r\n    },\r\n\r\n\t/**\r\n     * Get\r\n\t *\r\n\t * @method get\r\n\t * @param jsonResult\r\n\t *" +
                    "/\r\n    get: function (jsonResult) {\r\n        if (jsonResult.UserMessage && jsonR" +
                    "esult.UserMessage.IsSuccess) {\r\n            if (jsonResult.Data != null) {\r\n    " +
                    "            ");
            
            #line 282 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.displayResult(jsonResult, sg.utls.OperationMode.SAVE);\r\n            } e" +
                    "lse {\r\n                modelData.UIMode(sg.utls.OperationMode.NEW);\r\n           " +
                    " }\r\n            ");
            
            #line 286 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.setkey();\r\n        }\r\n    },\r\n\r\n\t/**\r\n     * Update\r\n\t *\r\n\t * @method u" +
                    "pdate\r\n\t * @param jsonResult\r\n\t */\r\n    update: function (jsonResult) {\r\n       " +
                    " if (jsonResult.UserMessage.IsSuccess) {\r\n            ");
            
            #line 298 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.displayResult(jsonResult, sg.utls.OperationMode.SAVE);\r\n            ");
            
            #line 299 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.setkey();\r\n        }\r\n        sg.utls.showMessage(jsonResult);\r\n    },\r" +
                    "\n\r\n\t/**\r\n     * Create\r\n\t *\r\n\t * @method create\r\n\t * @param jsonResult\r\n\t */\r\n  " +
                    "  create: function (jsonResult) {\r\n        ");
            
            #line 311 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.displayResult(jsonResult, sg.utls.OperationMode.NEW);\r\n        ");
            
            #line 312 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 312 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model.isModelDirty.reset();\r\n        ");
            
            #line 313 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.setkey();\r\n        sg.controls.Focus($(\"#txt");
            
            #line 314 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("\"));\r\n    },\r\n\r\n\t/**\r\n     * Delete\r\n\t *\r\n\t * @method delete\r\n\t * @param jsonResu" +
                    "lt\r\n\t */\r\n    delete: function (jsonResult) {\r\n        if (jsonResult.UserMessag" +
                    "e.IsSuccess) {\r\n            ");
            
            #line 325 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.displayResult(jsonResult, sg.utls.OperationMode.NEW);\r\n            ");
            
            #line 326 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 326 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model.isModelDirty.reset();\r\n            ");
            
            #line 327 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write(@"UISuccess.setkey();
        }
        sg.utls.showMessage(jsonResult);
    },

	/**
     * Display Result
	 *
	 * @method displayResult
	 * @param jsonResult
	 * @param uiMode
	 */
    displayResult: function (jsonResult, uiMode) {
        if (jsonResult != null) {
            if (!");
            
            #line 341 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.hasKoBindingApplied) {\r\n                ");
            
            #line 342 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 342 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model = ko.mapping.fromJS(jsonResult);\r\n                ");
            
            #line 343 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.hasKoBindingApplied = true;\r\n                modelData = ");
            
            #line 344 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 344 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model.Data;\r\n                ");
            
            #line 345 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("ObservableExtension(");
            
            #line 345 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 345 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model, uiMode);\r\n                ");
            
            #line 346 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 346 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model.isModelDirty = new ko.dirtyFlag(modelData, ");
            
            #line 346 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.ignoreIsDirtyProperties);\r\n                ko.applyBindings(");
            
            #line 347 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 347 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model);\r\n            } else {\r\n                ko.mapping.fromJS(jsonResult, ");
            
            #line 349 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 349 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model);\r\n                modelData.UIMode(uiMode);\r\n                if (uiMode !=" +
                    " sg.utls.OperationMode.NEW) {\r\n                    ");
            
            #line 352 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 352 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model.isModelDirty.reset();\r\n                }\r\n            }\r\n\r\n            if (" +
                    "!");
            
            #line 356 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.isKendoControlNotInitialised) {\r\n                ");
            
            #line 357 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.isKendoControlNotInitialised = true;\r\n                ");
            
            #line 358 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.initDropDownList();\r\n                ");
            
            #line 359 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"

                    // Iterate XML, if any
                    if (xmlLayout != null)
                    {
                        // Iterate drop down widgets, if any
                        if (widgets.ContainsKey("Dropdown"))
                        {
                            foreach (var widget in widgets["Dropdown"])
                            {
                                WriteLine(new string(' ', 16) + "$(\"#ddl" + widget + "\").data(\"kendoDropDownList\").value(modelData." + widget + "(jsonResult.Data." + widget + "));");
                            }
                        }
                    }
                
            
            #line default
            #line hidden
            this.Write("            } else {\r\n                // \r\n                ");
            
            #line 375 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"

                    // Iterate XML, if any
                    if (xmlLayout != null)
                    {
                        // Iterate drop down widgets, if any
                        if (widgets.ContainsKey("Dropdown"))
                        {
                            foreach (var widget in widgets["Dropdown"])
                            {
                                WriteLine(new string(' ', 16) + "$(\"#ddl" + widget + "\").data(\"kendoDropDownList\").value(modelData." + widget + "());");
                            }
                        }
                    }
                
            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n    },\r\n\r\n\t/**\r\n     * Initial Load\r\n\t *\r\n\t * @method i" +
                    "nitialLoad\r\n\t * @param result\r\n\t */\r\n    initialLoad: function (result) {\r\n     " +
                    "   if (result) {\r\n            ");
            
            #line 400 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UISuccess.displayResult(result, sg.utls.OperationMode.NEW);\r\n        } else {\r\n  " +
                    "          sg.utls.showMessageInfo(sg.utls.msgType.ERROR, ");
            
            #line 402 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Resources.ProcessFailedMessage);\r\n        }\r\n        sg.controls.Focus($(\"#txt");
            
            #line 404 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("\"));\r\n    },\r\n\r\n\r\n\t/**\r\n     * Is New\r\n\t *\r\n\t * @method isNew\r\n\t * @param model\r\n" +
                    "\t */\r\n    isNew: function (model) {\r\n        if (model.");
            
            #line 415 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("() === null) {\r\n           return true;\r\n        }\r\n        return false;\r\n    }\r" +
                    "\n};\r\n\r\n// Initial Entry\r\n$(function () {\r\n    ");
            
            #line 424 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.init();\r\n    $(window).on(\'beforeunload\', function () {\r\n        if (globalRes" +
                    "ource.AllowPageUnloadEvent && ");
            
            #line 426 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("UI.");
            
            #line 426 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Model.isModelDirty.isDirty()) {\r\n            return jQuery(\'<div />\').html(jQuery" +
                    ".validator.format(globalResource.SaveConfirm2, ");
            
            #line 427 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localEntityName));
            
            #line default
            #line hidden
            this.Write("Resources.");
            
            #line 427 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyFieldName));
            
            #line default
            #line hidden
            this.Write("Title)).text();\r\n        }\r\n    });\r\n});\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Development\Branches\SDK\Sage300-SDK\src\wizards\CodeGenerationWizard\Templates\Flat\Script\Behaviour.tt"

private global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.BusinessView _viewField;

/// <summary>
/// Access the view parameter of the template.
/// </summary>
private global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.BusinessView view
{
    get
    {
        return this._viewField;
    }
}

private global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.Settings _settingsField;

/// <summary>
/// Access the settings parameter of the template.
/// </summary>
private global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.Settings settings
{
    get
    {
        return this._settingsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool viewValueAcquired = false;
if (this.Session.ContainsKey("view"))
{
    this._viewField = ((global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.BusinessView)(this.Session["view"]));
    viewValueAcquired = true;
}
if ((viewValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("view");
    if ((data != null))
    {
        this._viewField = ((global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.BusinessView)(data));
    }
}
bool settingsValueAcquired = false;
if (this.Session.ContainsKey("settings"))
{
    this._settingsField = ((global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.Settings)(this.Session["settings"]));
    settingsValueAcquired = true;
}
if ((settingsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("settings");
    if ((data != null))
    {
        this._settingsField = ((global::Sage.CA.SBS.ERP.Sage300.CodeGenerationWizard.Settings)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class BehaviourBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
