//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage300InquiryConfigurationGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage300InquiryConfigurationGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adhoc.
        /// </summary>
        internal static string Adhoc {
            get {
                return ResourceManager.GetString("Adhoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Credentials.
        /// </summary>
        internal static string ApplicationCredentials {
            get {
                return ResourceManager.GetString("ApplicationCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to proceed?.
        /// </summary>
        internal static string AreYouSureYouWishToProceed {
            get {
                return ResourceManager.GetString("AreYouSureYouWishToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified).
        /// </summary>
        internal static string ChineseSimplified {
            get {
                return ResourceManager.GetString("ChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Traditional).
        /// </summary>
        internal static string ChineseTraditional {
            get {
                return ResourceManager.GetString("ChineseTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this application.
        /// </summary>
        internal static string CloseTip {
            get {
                return ResourceManager.GetString("CloseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Company is required..
        /// </summary>
        internal static string CompanyIsRequired {
            get {
                return ResourceManager.GetString("CompanyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Sage 300 company.
        /// </summary>
        internal static string CompanyTip {
            get {
                return ResourceManager.GetString("CompanyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLSX Files (InquiryConfiguration*.xlsx)|InquiryConfiguration*.xlsx.
        /// </summary>
        internal static string ConfigurationFileFilter {
            get {
                return ResourceManager.GetString("ConfigurationFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of the configuration files was successful!.
        /// </summary>
        internal static string ConfigurationGenerationSuccessful {
            get {
                return ResourceManager.GetString("ConfigurationGenerationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM.
        /// </summary>
        internal static string CRM {
            get {
                return ResourceManager.GetString("CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLSX Files (Sage300ViewColumnSetting*.xlsx)|Sage300ViewColumnSetting*.xlsx.
        /// </summary>
        internal static string DatasourceColumnSettingFileFilter {
            get {
                return ResourceManager.GetString("DatasourceColumnSettingFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource.
        /// </summary>
        internal static string DatasourceConfigurationFile {
            get {
                return ResourceManager.GetString("DatasourceConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Datasource Configuration File specification is required..
        /// </summary>
        internal static string DatasourceConfigurationFileIsRequired {
            get {
                return ResourceManager.GetString("DatasourceConfigurationFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Datasource Configuration file path.
        /// </summary>
        internal static string DatasourceConfigurationFileTip {
            get {
                return ResourceManager.GetString("DatasourceConfigurationFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying output folder....
        /// </summary>
        internal static string DisplayingOutputFolder {
            get {
                return ResourceManager.GetString("DisplayingOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying the output log file....
        /// </summary>
        internal static string DisplayingOutputLogFile {
            get {
                return ResourceManager.GetString("DisplayingOutputLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display log file on program completion..
        /// </summary>
        internal static string DisplayLogFileOnCompletion {
            get {
                return ResourceManager.GetString("DisplayLogFileOnCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display output folder on program completion..
        /// </summary>
        internal static string DisplayOutputFolderOnCompletion {
            get {
                return ResourceManager.GetString("DisplayOutputFolderOnCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed with the file generation process.
        /// </summary>
        internal static string GenerateTip {
            get {
                return ResourceManager.GetString("GenerateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry Configuration.
        /// </summary>
        internal static string InquiryConfiguration {
            get {
                return ResourceManager.GetString("InquiryConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry Configuration Generator.
        /// </summary>
        internal static string InquiryConfigurationGenerator {
            get {
                return ResourceManager.GetString("InquiryConfigurationGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username, password, company and version..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a required field..
        /// </summary>
        internal static string IsRequiredTemplate {
            get {
                return ResourceManager.GetString("IsRequiredTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a valid, existing file..
        /// </summary>
        internal static string IsValidFileTemplate {
            get {
                return ResourceManager.GetString("IsValidFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a valid Sage 300 password..
        /// </summary>
        internal static string IsValidPassword {
            get {
                return ResourceManager.GetString("IsValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a valid Sage 300 user..
        /// </summary>
        internal static string IsValidUsername {
            get {
                return ResourceManager.GetString("IsValidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Support.
        /// </summary>
        internal static string LanguageSupport {
            get {
                return ResourceManager.GetString("LanguageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OptionTip {
            get {
                return ResourceManager.GetString("OptionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder location where you wish to save the output of this program. This folder will be relative to (within) the Root folder defined previously..
        /// </summary>
        internal static string OutputFolderBrowserDescription {
            get {
                return ResourceManager.GetString("OutputFolderBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputPath.
        /// </summary>
        internal static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Output directory is required..
        /// </summary>
        internal static string OutputPathIsRequired {
            get {
                return ResourceManager.GetString("OutputPathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OutputPathTip {
            get {
                return ResourceManager.GetString("OutputPathTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Sage 300 password is required..
        /// </summary>
        internal static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Sage 300 password.
        /// </summary>
        internal static string PasswordTip {
            get {
                return ResourceManager.GetString("PasswordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure no errors occurred by viewing the output log file..
        /// </summary>
        internal static string PleaseEnsureNoErrorsOccurred {
            get {
                return ResourceManager.GetString("PleaseEnsureNoErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Cancel&apos; to abort..
        /// </summary>
        internal static string PressCancelToAbort {
            get {
                return ResourceManager.GetString("PressCancelToAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;OK&apos; to proceed..
        /// </summary>
        internal static string PressOKToProceed {
            get {
                return ResourceManager.GetString("PressOKToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has completed..
        /// </summary>
        internal static string ProgramRunCompleted {
            get {
                return ResourceManager.GetString("ProgramRunCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Root folder location where all input and output for this application will be located..
        /// </summary>
        internal static string RootFolderBrowserDescription {
            get {
                return ResourceManager.GetString("RootFolderBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RootPath.
        /// </summary>
        internal static string RootPath {
            get {
                return ResourceManager.GetString("RootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Root directory is required..
        /// </summary>
        internal static string RootPathIsRequired {
            get {
                return ResourceManager.GetString("RootPathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root working folder.
        /// </summary>
        internal static string RootPathTip {
            get {
                return ResourceManager.GetString("RootPathTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current settings to the application configuration file.
        /// </summary>
        internal static string SaveSettingsTip {
            get {
                return ResourceManager.GetString("SaveSettingsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings were saved successfully..
        /// </summary>
        internal static string SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Script Name.
        /// </summary>
        internal static string SQLScriptName {
            get {
                return ResourceManager.GetString("SQLScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SQL Script Name is required..
        /// </summary>
        internal static string SQLScriptNameIsRequired {
            get {
                return ResourceManager.GetString("SQLScriptNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SQLScriptNameTip {
            get {
                return ResourceManager.GetString("SQLScriptNameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string TemplateConfigurationFile {
            get {
                return ResourceManager.GetString("TemplateConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Template Configuration File specification is required..
        /// </summary>
        internal static string TemplateConfigurationFileIsRequired {
            get {
                return ResourceManager.GetString("TemplateConfigurationFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Template Configuration file path.
        /// </summary>
        internal static string TemplateConfigurationFileTip {
            get {
                return ResourceManager.GetString("TemplateConfigurationFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log file is located here: &apos;{0}&apos;..
        /// </summary>
        internal static string TheLogFileIsLocatedHereTemplate {
            get {
                return ResourceManager.GetString("TheLogFileIsLocatedHereTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Sage 300 username is required..
        /// </summary>
        internal static string UsernameIsRequired {
            get {
                return ResourceManager.GetString("UsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Sage 300 user.
        /// </summary>
        internal static string UserTip {
            get {
                return ResourceManager.GetString("UserTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there appear to be one (or more) validation errors..
        /// </summary>
        internal static string ValidationErrors1 {
            get {
                return ResourceManager.GetString("ValidationErrors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix before attempting to generate output files..
        /// </summary>
        internal static string ValidationErrors2 {
            get {
                return ResourceManager.GetString("ValidationErrors2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Version is required..
        /// </summary>
        internal static string VersionIsRequired {
            get {
                return ResourceManager.GetString("VersionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid Sage 300 version.
        /// </summary>
        internal static string VersionTip {
            get {
                return ResourceManager.GetString("VersionTip", resourceCulture);
            }
        }
    }
}
